### ISSUE TITLE
Password recovery + activation issue

### ISSUE THREAD

**Issue by aminembarki** [DivanteLtd/open-loyalty#10]
password recovery link+ actions doesn't work

**Comment by colejarczyk** [comment]
Hi,

I've fixed it here: https://github.com/DivanteLtd/open-loyalty/pull/15

I guess you have already installed application. So you need to regenerate file parameters.yml in backend/app/config or just edit lines according to the parameters.yml.dist from the pull request. You need to add an exclamation mark after the hash char in four lines:

```
frontend_password_reset_url
frontend_activate_account_url
env(FRONTEND_PASSWORD_RESET_URL)
env(FRONTEND_ACTIVATE_ACCOUNT_URL)
```

For example change 
```http://localhost:8182/#/password/reset``` 
to the 
```http://localhost:8182/#!/password/reset```
