### ISSUE TITLE
First time setup using Docker (windows 10) not working

### ISSUE THREAD

**Issue by shaurya157** [DivanteLtd/open-loyalty#101]
Hey guys, I'm trying to run the program on Docker via Windows 10 on a virtual machine (since I have a windows 10 laptop).

I've confirmed that docker is working as intended by following their getting started guide, but when I run `docker-compose up` on the cloned open loyalty repo this is the error I get:

`ERROR: Service 'php' failed to build: The command '/bin/sh -c chmod a+x init.sh && rm web/app_dev.php && composer install --no-dev -o --prefer-dist && bin/console assets:install && rm web/config.php && chown -R www-data:www-data /var/www/openloyalty/var' returned a non-zero code: 127`

I tried to search around for what's causing this but I'm not able to find a definitive answer (am new to docker). Has anyone else faced this?

**Comment by catbuilts** [comment]
I think it's the same with #94.

When cloning, it misses some files. You should download the zip file.

**Comment by shaurya157** [comment]
@catbuilts I've downloaded the zip version and tried to run using docker but I'm still not able to compile the app successfully. Here's what I get: 

![image](https://user-images.githubusercontent.com/17190054/39283560-65eed70a-4941-11e8-85f4-af7a2d805dd7.png)

**Comment by shaurya157** [comment]
Okay so I stopped trying to run it on a local machine and set up an EC2 instance instead and run it remotely by connecting to it via SSH (works same as a linux machine). I also used the zip file instead of the cloned file, but the docker-compose up throws me this error

![image](https://user-images.githubusercontent.com/17190054/39286188-0dbdaf30-494f-11e8-9bcb-964f276bfacb.png)

**Comment by colejarczyk** [comment]
Seems you have a problem with permissions to files. Please run "ls -la" on the backend directory to see it's writable.
