### ISSUE TITLE
npm install -g yarn' returned a non-zero code: 1

### ISSUE THREAD

**Issue by ismailyenigul** [DivanteLtd/open-loyalty#102]
Hi,

I am trying to build 2.4.0 release,

when I issue the following command, frontend docker build fails
~/open-loyalty-2.4.0/docker$ docker-compose -f docker-compose.dev.yml  -f docker-compose.yml up -d

npm@3.8.6 /usr/local/lib/node_modules/npm
`-- fs-extra@6.0.0  extraneous

npm info ok 
npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.12.0
npm ERR! Linux 4.4.0-1052-aws
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yarn"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! Unexpected token ...
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm/npm-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c cd $(npm root -g)/npm     && npm install fs-extra     && sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js     && npm install -g yarn' returned a non-zero code: 1

any idea?

Thanks

**Comment by colejarczyk** [comment]
Hi,

Please run 'docker-compose down --rmi all" and run again "docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up"

It's a first time I see this error and don't know why you're facing it.

**Comment by ismailyenigul** [comment]
Hi,
the result is same.
I test with open-loyalty-2.4.0

# docker-compose down --rmi all
Stopping open_loyalty_frontend ... done
Stopping open_loyalty_backend  ... done
Stopping open_loyalty_mail     ... done
Stopping open_loyalty_db       ... done
Stopping open_loyalty_elk      ... done
Removing open_loyalty_frontend ... done
Removing open_loyalty_backend  ... done
Removing open_loyalty_mail     ... done
Removing open_loyalty_db       ... done
Removing open_loyalty_elk      ... done
Removing network docker_default
Removing image elasticsearch:2.2
Removing image postgres:9
Removing image mailhog/mailhog
Removing image docker_php
Removing image docker_nginx

docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up"

npm WARN frontend No license field.
npm info ok 
sed: can't read ./lib/utils/rename.js: No such file or directory
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c npm install fs-extra     && sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js     && npm install -g yarn' returned a non-zero code: 2

**Comment by colejarczyk** [comment]
Hi @ismailyenigul 

Do you have still a problem with running an Open Loyalty?

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
