### ISSUE TITLE
Developers URL access

### ISSUE THREAD

**Issue by shuklapriya** [DivanteLtd/open-loyalty#104]
Getting an error after running this command to get the URL access for developers:
docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up

Response:
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yarn"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! Unexpected token ...
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm/npm-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c cd $(npm root -g)/npm     && npm install fs-extra     && sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js     && npm install -g yarn' returned a non-zero code: 1

**Comment by colejarczyk** [comment]
Hi,

Please run 'docker-compose down --rmi all" and run again "docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up"

It's a first time I see this error and don't know why you're facing it.

**Comment by colejarczyk** [comment]
Hi @shuklapriya 

Do you have still a problem with running an Open Loyalty?

**Comment by stanley87** [comment]
my side also has same issue,
using windows 10
using vagrant
@colejarczyk

**Comment by george-haddad** [comment]
> Hi,
>
>Please run 'docker-compose down --rmi all" and run again "docker-compose -f docker/docker compose.yml -f docker/docker-compose.dev.yml up"
>
>It's a first time I see this error and don't know why you're facing it.

I have the same error as @shuklapriya and I just executed the above command and I still get the same error. I'm running this under windows 10 with docker version `18.03.1-ce, build 9ee9f40`

```bash
npm@3.8.6 /usr/local/lib/node_modules/npm
`-- fs-extra@6.0.1  extraneous

npm info ok
npm info it worked if it ends with ok
npm info using npm@3.8.6
npm info using node@v5.12.0
npm ERR! Linux 4.9.87-linuxkit-aufs
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "yarn"
npm ERR! node v5.12.0
npm ERR! npm  v3.8.6

npm ERR! Unexpected token ...
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/local/lib/node_modules/npm/npm-debug.log
ERROR: Service 'frontend' failed to build: The command '/bin/sh -c cd $(npm root -g)/npm     && npm install fs-extra     && sed -i -e s/graceful-fs/fs-extra/ -e s/fs.rename/fs.move/ ./lib/utils/rename.js     && npm install -g yarn' returned a non-zero code: 1
```

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
