### ISSUE TITLE
Login Using Default Credentials

### ISSUE THREAD

**Issue by shuklapriya** [DivanteLtd/open-loyalty#105]
Request: trying to login using default admin credentials, username: admin and password: open

Response: open_loyalty_db | FATAL:  password authentication failed for user "root"
open_loyalty_db | DETAIL:  Role "root" does not exist.
open_loyalty_db | 	Connection matched pg_hba.conf line 95: "host all all all md5"

**Comment by colejarczyk** [comment]
Hi,

The credentials you mentioned "admin" and "open" are for login into administration panel. If you want to log in to the database, please use credentials from file app/config/parameters.yml. Usually it's "openloyalty" as a username, pasword and database name.

If you can't log in to the administration panel, please run a command "docker-compose exec php phing setup" to initialize a database.

**Comment by colejarczyk** [comment]
Closed after a long time without response
