### ISSUE TITLE
get admin,client panel in locally browser

### ISSUE THREAD

**Issue by anggunwibowo** [DivanteLtd/open-loyalty#106]
Dear Admin,

I've trying running open-loyalty in locally, it's seem look like ok, the last line of command is:
open_loyalty_mail : [APIv1] KEEPALIVE /api/v1/events and always running in a several time,
I would like to show interface panel open-loyalty in browser with vhosts I had created in hosts
but url access showing openloyalty.localhost refused to connect.

please your help , thank you

**Comment by colejarczyk** [comment]
Hi @anggunwibowo 
It's perfectly fine to see KEEPALIVE messages of MailHog in the log. Please run command "docker-compose ps" to see if all docker containers are running. Also to use openloyalty.localhost domain you need to add it to the /etc/hosts and point to 127.0.0.1, if you use Linux.
