### ISSUE TITLE
Compiling Frontend Packag

### ISSUE THREAD

**Issue by arfeen** [DivanteLtd/open-loyalty#107]
Hi

I have no other place to ask this question. I want to know about compiling frontend package. Right now, I'm running frontend package as 'npm start' and it starts the package, for some reason, it does not last too long and breaks and I have to again run it using 'npm start'. Is there anyway to compile the entire package and run it as simple HTML ? How can I do that ?

Arfeen

**Comment by colejarczyk** [comment]
Hi @arfeen,

Look at file frontend/package.json and section "scripts".

The "npm start" runs a webpack-dev-server so you can see changes in the code immediately. To build a production version just run "npm build".

**Comment by arfeen** [comment]
Thanks @colejarczyk I did that. I haven't worked on Node/Angular much. Just a quick question. The build folder has a new code base now, again it needs NPM START in that folder, am I right ?

**Comment by colejarczyk** [comment]
The build folder has a static code. Just plain HTML, javascript and CSS files. So it may be served by Nginx or any other web server. NPM is not needed at all.

**Comment by arfeen** [comment]
@colejarczyk Thanks. It worked and I got it now.
