### ISSUE TITLE
How to update new version without losing database

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#110]
Hi,

I have been working with Openloyalty for a while.
I realized that every time, when a new version comes out, I have to re-install it by following commands:

> docker-compose up
> docker-compose exec php phing setup

The second command will delete all the database and re-create a brand new one.
So, **when a new version is available, is there any way that I can keep my Openloyalty up-to-date and my database intact?**
I dont want to lose my database when Openloyalty updates new features.
I tried not to run the second command, but it turned out errors. 

Thank you.

**Comment by colejarczyk** [comment]
Hi @catbuilts 

Sure you can. Just don't run phing setup as it cleans a database and event store. You should run follow commands:
```bin/console cache:clear```
It clears cache

```bin/console doctrine:schema:update --force ```
It's a command to update scheme in PostgreSQL without losing data.

``` bin/console oloy:user:projections:index:create --drop-old -n```
It deletes all indexes in ElasticSearch and creates a new one.

``` bin/console oloy:utility:read-models:recreate```
It recreates all data from event store to ElasticSearch, so the read model is up-to-date.

Now you should have all required updates to run a new version in Open Loyalty.

Sometimes we release a new version with BC breaks so please look at the UPGRADE-*.*.md files.

**Comment by catbuilts** [comment]
Hi @colejarczyk 
Thanks for your support.
I have run those commands. But I couldn't  log in admin panel, some errors occurred:

> [2018-05-29 06:11:34] request.CRITICAL: Uncaught PHP Exception InvalidArgumentException: "The directory "/var/www/openloyalty/var/cache/prod/jms_serializer" is not writable." at /var/www/openloyalty/vendor/jms/metadata/src/Metadata/Cache/FileCache.php line 17 {"exception":"[object] (InvalidArgumentException(code: 0): The directory \"/var/www/openloyalty/var/cache/prod/jms_serializer\" is not writable. at /var/www/openloyalty/vendor/jms/metadata/src/Metadata/Cache/FileCache.php:17)"} []
>  [2018-05-29 06:11:34] request.CRITICAL: Exception thrown when handling an exception (RuntimeException: Unable to write in the cache directory (/var/www/openloyalty/var/cache/prod/twig/d6). at /var/www/openloyalty/vendor/twig/twig/lib/Twig/Cache/Filesystem.php line 59) {"exception":"[object] (RuntimeException(code: 0): Unable to write in the cache directory (/var/www/openloyalty/var/cache/prod/twig/d6). at /var/www/openloyalty/vendor/twig/twig/lib/Twig/Cache/Filesystem.php:59)"} []

**Comment by tjurczak** [comment]
Hi @catbuilts,

I suppose that your problem is related to file permissions. You had to run some command with root privileges. Now you can change permission using `chmod -R www-data:www-data var/cache`. Remeber that every command like phing or bin/console should be called as www-data user.

**Comment by catbuilts** [comment]
Hi @tjurczak

Thank you, It worked !
