### ISSUE TITLE
Translation not reflected in Customer panel

### ISSUE THREAD

**Issue by pantianhon** [DivanteLtd/open-loyalty#111]
Hi,

I have edited the translation file under Settings -> Translations. 

It works well in the Admin panel. But the changes are not reflected in the Customer panel. Am I missing something? 

Cheers!

**Comment by colejarczyk** [comment]
Hi @pantianhon 

I will explain how translations work. When you go to the client panel for the first time, it calls API to get translations and then stores it in local storage. Next time you visit client panel, it takes translations from local storage. So if you change translations then you have to clear local storage.

Here is a screen:
![localstorage](https://user-images.githubusercontent.com/3582562/41529982-07c779e8-72ef-11e8-9296-32e1e2044eaa.png)

**Comment by pantianhon** [comment]
Okay I've clear the local storage and it works. Thank you.
