### ISSUE TITLE
Installation on premise server

### ISSUE THREAD

**Issue by stanley87** [DivanteLtd/open-loyalty#112]
Hi base on the installation section, only docker/vagrant installation available, can we has the full complete installation guideline to setup at our own server directly?what is the prerequisites for single server installation without using docker/vagrant ?

**Comment by colejarczyk** [comment]
Hi @stanley87 

We do not support installing Open Loyalty without Vagrant or Docker. If you want to install it on your server directly then you can use Dockerfiles as a reference how to install all necessary and configure required software to run Open Loyalty directly on the server.

For example:
https://github.com/DivanteLtd/open-loyalty/blob/master/docker/prod/php/fpm-dockerfile

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
