### ISSUE TITLE
Using mysql but not posgres

### ISSUE THREAD

**Issue by stanley87** [DivanteLtd/open-loyalty#114]
Hi team,
Can we use mysql for the database but not using posgres?How is the step to migrate to mysql database for open-loyalty>

**Comment by colejarczyk** [comment]
Hi @stanley87 

We never tested Open Loyalty against MySQL so I can't tell it will work. We're using Doctrine ORM so it should work out of the box if you change docker file from PostgreSQL to the MySQL and update credentials to the database in the parameters.yml.dist fie

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
