### ISSUE TITLE
Please write step for configure open-loyalty project without docker

### ISSUE THREAD

**Issue by hardikpatel1244** [DivanteLtd/open-loyalty#115]
I tried to setup without docker but got below error when run php bin/console doctrine:fixtures:load

$ php bin/console doctrine:fixtures:load

Careful, database will be purged. Do you want to continue y/N ?y
  > purging database
  > loading [0] OpenLoyalty\Bundle\UserBundle\DataFixtures\ORM\LoadRoleData
  > loading [0] OpenLoyalty\Bundle\LevelBundle\DataFixtures\ORM\LoadLevelData
  > loading [0] OpenLoyalty\Bundle\SettingsBundle\DataFixtures\ORM\LoadSettingsData
  > loading [0] OpenLoyalty\Bundle\EarningRuleBundle\DataFixtures\ORM\LoadEarningRuleData
  > loading [0] OpenLoyalty\Bundle\PosBundle\DataFixtures\ORM\LoadPosData
  > loading OpenLoyalty\Bundle\CampaignBundle\DataFixtures\ORM\LoadCampaignData
  > loading [0] OpenLoyalty\Bundle\EmailSettingsBundle\DataFixtures\ORM\LoadEmailsData
  > loading [1] OpenLoyalty\Bundle\UserBundle\DataFixtures\ORM\LoadUserData
23:45:48 ERROR     [console] Error thrown while running command "doctrine:fixtures:load". Message: "No alive nodes found in your cluster" ["exception" => Elasticsearch\Common\Exceptions\NoNodesAvailableException { …},"command" => "doctrine:fixtures:load","message" => "No alive nodes found in your cluster"] []

In StaticNoPingConnectionPool.php line 51:
                                        
  No alive nodes found in your cluster

**Comment by colejarczyk** [comment]
Hi @hardikpatel1244 

Seems that Open Loyalty has no connection to the elasticsearch which is required.

**Comment by hardikpatel1244** [comment]
Can you write step, where need put frontend folder all things, step by step please

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
