### ISSUE TITLE
Coupons Usage / Unique Codes

### ISSUE THREAD

**Issue by arfeen** [DivanteLtd/open-loyalty#117]
Again, there is no forum to discuss this feature, so posting here. Do guide us to any forum where we can discuss certain issues.

1. How do I create coupons using CSV file. What is the CSV file format. I can't get any info about it anywhere.

2. How would you create unique coupon codes, so that each customer will get its different codes.

3. How do we check if the copon code exists, since we need to make a process of redemtion via API, so we need to see if the coupon entered by the customer is the correct one.

Thanks.

**Comment by arfeen** [comment]
In addition to that:

1. How would I define monitory value in the campaign ? Although I have defined a cost in points, but there will be some monitory reward, say for example, purchase discounts. How would I know the monitory value ?

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
