### ISSUE TITLE
Change openloyalty.localhost to an IP address or custom domain

### ISSUE THREAD

**Issue by mohan-nishit** [DivanteLtd/open-loyalty#119]
Hi,
I want to test the effectiveness of this LMS with the magento integration at https://github.com/DivanteLtd/magento-open-loyalty. How can I change the API URL? I have tried changing the url at frontend/src/config.js, frontend/rancher/entrypoint.sh etc., but `docker-compose up` doesn't change anything in the frontend. The URL remains http://openloyalty.localhost/api

Is there any way to change this?

**Comment by tjurczak** [comment]
Hi,

please note, that `docker-composer up` run images from docker hub, so your changes are ignored. If you want to change code you have to work as developer and run `docker-compose -f docker/docker-compose.dev.yml up` (read details https://github.com/DivanteLtd/open-loyalty#for-developers). Then docker will prepare images using your changed source code.

**Comment by mohan-nishit** [comment]
Hi,
Thank you for this info. I am relatively new to docker, and it would help greatly if you could tell me where to make the changes to the URL and deploy the updated code.
