### ISSUE TITLE
ERROR: .IOError: [Errno 2] No such file or directory: u'./docker/docker-compose.yml'

### ISSUE THREAD

**Issue by MunirajM** [DivanteLtd/open-loyalty#120]
Hi,

I have executed the below commands,
```
vagrant up
vagrant ssh
```
Then executed the command `docker-compose -f docker/docker-compose.yml up -d` and getting the error 
> ERROR: .IOError: [Errno 2] No such file or directory: u'./docker/docker-compose.yml'

I have checked the issues queue and not able to find any related issues. It was working fine before and stopped working after I have restarted the Laptop.

Also, noted the below warning while doing `vagrant up`
> vm: sed: can't read /opt/open-loyalty/frontend/src/config.js: No such file or directory

Am I missing anything?

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
