### ISSUE TITLE
Customer Import XML format

### ISSUE THREAD

**Issue by mohan-nishit** [DivanteLtd/open-loyalty#122]
Hi,

For importing customers, where can I get the XML format needed?

**Comment by MrHubert** [comment]
Hey, you can check this one:

<?xml version="1.0" encoding="UTF-8"?>
<customers>
    <customer>
        <active>true</active>
        <sendActivationMail>false</sendActivationMail>
        <address>
            <address1>Kosciuszki 33</address1>
            <address2>Pl wilhelma</address2>
            <city>Wroclaw</city>
            <country>PL</country>
            <postal>55-344</postal>
            <street>Globalna 33</street>
        </address>
        <agreement1>true</agreement1>
        <agreement2>true</agreement2>
        <agreement3>true</agreement3>
        <birthDate>2018-02-03</birthDate>
        <company>
            <name>Company_Name</name>
            <nip>TAX ID</nip>
        </company>
        <email>jozek5443654d@example.com</email>
        <firstName>John</firstName>
        <lastName>Doe</lastName>
        <gender>male</gender>
        <labels>
            <label>
                <key>KeyLabel</key>
                <value>12345</value>
            </label>
            <label>
                <key>keyLabel</key>
                <value>labelValue</value>
            </label>
        </labels>
        <loyaltyCardNumber>3g4f543d4442</loyaltyCardNumber>
        <phone>+XX1234567890</phone>

        <posId>adcf9c44-7401-43b1-98b9-59cff2ca3af7</posId>
        <sellerId>00000000-0000-474c-b092-b0dd880c07e4</sellerId>
    </customer>
</customers>

**Comment by mohan-nishit** [comment]
Thank you.
