### ISSUE TITLE
Disabling Mailhog and adding SMTP server for email

### ISSUE THREAD

**Issue by mohan-nishit** [DivanteLtd/open-loyalty#123]
Hi,

How to disable mailhog and setup custom SMTP Servers? I have changed the mailer_* values in the parameters.yml file, but emails are still sent to Mailhog.

**Comment by eligiable** [comment]
I'm facing the same issue, is there any fix for this?

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
