### ISSUE TITLE
How can I remove validations for a field in a model?

### ISSUE THREAD

**Issue by mohan-nishit** [DivanteLtd/open-loyalty#124]
For instance, if I want to remove the validation for Last Name from Customer Details, how can I do this?

**Comment by tjurczak** [comment]
Hi,

you have to override `\OpenLoyalty\Bundle\UserBundle\Form\Type\CustomerRegistrationFormType` using some Symfony class override approaches and remove constraints from field `lastName`.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
