### ISSUE TITLE
"This coupon has been used"/"Used by Customers" checkboxes are not ticked for the second time use of the coupon

### ISSUE THREAD

**Issue by poniatowski** [DivanteLtd/open-loyalty#126]
"This coupon has been used"/"Used by Customers" checkboxes are not ticked for the second time use of the coupon. 

1) I have redeemed two this same campaigns. However, I wasn't able to mark as used the second campaigns. I have noticed that available campaigns don't have uniques ids. So when I was sending a request to mark coupon as used it was always referring to campaign ID. 

2) Also, I have noticed that new customers can't see old campaigns.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
