### ISSUE TITLE
Using endpoint GET  /api/customer with segment filter

### ISSUE THREAD

**Issue by mohan-nishit** [DivanteLtd/open-loyalty#127]
Hi, Is it possible to get users belonging to a certain **segment** from this API? I want to use this in combination with the hoursFromLastUpdate parameter for automating certain tasks. Can I specify the segmentId as a filter somehow?

**Comment by tjurczak** [comment]
Hi, 

it is possible.You have to use endpoint:
```
GET api/segment/00000000-0000-0000-0000-000000000011/customers
```
where 00000000-0000-0000-0000-000000000011 is segment ID.

**Comment by tjurczak** [comment]
Hi, at this moment API (segment endpoint) does not support that parameter.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
