### ISSUE TITLE
open_loyalty_db | ERROR:  relation "ol__settings" does not exist at character 241

### ISSUE THREAD

**Issue by mohan-nishit** [DivanteLtd/open-loyalty#128]
When I try to push users using xml file uploads, after a few minutes, I get a 504 timeout and upon doing a docker-compose down, and docker-compose up, the following error comes up. 

> open_loyalty_db | ERROR: relation "ol__settings" does not exist at character 241

I am using docker 17.06 on Ubuntu 16.04, and was runnig OpenLoyalty in dev mode. This issue has occurred before as well.

I have the latest release of OL.

**Comment by mohan-nishit** [comment]
Also, a suggestion for improvement, maybe a panel for exporting customer data so that we can have backups.

**Comment by tjurczak** [comment]
Hi,

I am not sure what happend but I will try to clarify:
1) If you use developer mode then nginx will occure error (504) when some action takes more than 60 seconds. I suppose that you have tried to import more than 100 users.
2) In developer mode you have to run application as:
`docker-compose -f docker-compose.dev.yml up`
and flush containers as:
`docker-compose -f docker-compose.dev.yml down`
3) Warning (ERROR: relation "ol__settings" does not exist at character 241) which has been mentioned by you is normal and is not related to you problem. Postgresql has enabled full log and some migration script causes that warnings.

Additionally thanks for suggestions.

**Comment by mohan-nishit** [comment]
Hi @tjurczak ,
Unfortunately, I had to reset the demo data (php phing demo), however, since I will be entering the data again, I will post back in case this happens. 
You are right about more than a hundred customers, I was uploading 10 files with about 200 customers each. In each case, the 504 timeout happened, while the data was uploaded successfully. The issue is that once I see this warning "ERROR: relation "ol__settings" does not exist at character 241", the backend stops functioning and throws 500 server errors, and this is what I see in the terminal:

open_loyalty_backend | 1.2.3.4 -  18/Sep/2018:11:34:14 +0000 "GET /app.php" 500
open_loyalty_db | ERROR:  relation "ol__settings" does not exist at character 241
open_loyalty_db | STATEMENT:  SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.json_value AS json_value_3, t0.boolean_value AS boolean_value_4, t0.integer_value AS integer_value_5, t0.json_value AS json_value_6, t0.string_value AS string_value_7 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'filesettingentry', 'booleansettingentry', 'integersettingentry', 'jsonsettingentry', 'stringsettingentry') LIMIT 1
open_loyalty_backend | 1.2.3.4 -  18/Sep/2018:11:34:14 +0000 "POST /app.php" 500

Thanks for the support. From a production standpoint, (and I ask this question being a MySQL user previously) is there any way to take regular DB dumps? I tried a pg_dumpall from the PGSQL container but I could not get the actual customer data.

Also, any recommended hardware specs for the instance for about 100,000 customer?

**Comment by mohan-nishit** [comment]
@tjurczak This happened again. I had started dev mode with:

> docker-compose -f docker-compose.dev.yml up

And I took down the containers with:

> docker-compose -f docker-compose.dev.yml down

The result was the same. 

> open_loyalty_db | ERROR: relation "ol__settings" does not exist at character 241

Could this be a build issue?

**Comment by tjurczak** [comment]
Hi,

1. If you want to import more data using import you should consider to use CLI command to do it. Importing data from UI does not support import a lot of data, because of some security limitation (nginx max execution time, php-fpm timeout, php max execution time). This settings depend on configuration for example on development environment, API request is killed after 30 seconds.

Try to log in on php container:
`docker exec -it open_loyalty_backend bash` 
Container name depends on type of environemnt - production/development.

then:
`su www-data`
and
`bin/console oloy:customer:import app/var/import/customers.xml`

2.

> Thanks for the support. From a production standpoint, (and I ask this question being a MySQL user previously) is there any way to take regular DB dumps? I tried a pg_dumpall from the PGSQL container but I could not get the actual customer data.

pg_dump or similar functions are OK, but please notice that CQRS pattern has been used in Open Loyalty architecture. It means that data is stored in database (events) and elasticsearch as readmodel (list of customers etc.). You should only backup database because readmodel can be rebuilt using `phing migrate`.

**Comment by tjurczak** [comment]
> I have narrowed it down to elasticsearch being incapable of adding a high number of users to a certain level, and eventually resulting in a 504 timeout. Upon  stopping starting the containers again, there is a server error from the backend.

Try to reproduce this problem on local environemnt but now use CLI command. I tried and i imported 200 customers successfully.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
