### ISSUE TITLE
Vagrant recipe issue

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/open-loyalty#13]
After launching the Vagrant recipe there you get 2 issues:
- no composer executed - although it's in Dockerfile script 
- wrong permissions (not writeable) backend/var/cache - it's probably because Dockerfile for backend sets it up - if composer had been run I guess it created var/cache for it's purposes and maybe then the permission settings works just fine (because in git repo there is no var/cache folder at all - something must created it but with wrong permissions)

Tested on macosx @colejarczyk

**Comment by colejarczyk** [comment]
Hi @pkarw 

Please check out newest version. This issue has been already fixed.
