### ISSUE TITLE
Fresh install in to Docker on OS X and Ubuntu Nested Query errors

### ISSUE THREAD

**Issue by RaymondFeltham** [DivanteLtd/open-loyalty#130]
A fresh install into docker on both Ubuntu and Mac OSX when trying to access any cockpit, the status circle spins and in the log, we see:

openloyalty_elk | RemoteTransportException[[Rama-Tut][172.18.0.4:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"nested":{"path":"campaignPurchases","query":{"bool":{"must":[{"match":{"campaignPurchases.status":"inactive"}}],"must_not":[{"match":{"campaignPurchases.used":true}}],"filter":{"exists":{"field":"campaignPurchases.activeSince"}}}}}}}]]; nested: QueryParsingException[[nested] failed to find nested object under path [campaignPurchases]];
openloyalty_elk | Caused by: SearchParseException[failed to parse search source [{"query":{"nested":{"path":"campaignPurchases","query":{"bool":{"must":[{"match":{"campaignPurchases.status":"inactive"}}],"must_not":[{"match":{"campaignPurchases.used":true}}],"filter":{"exists":{"field":"campaignPurchases.activeSince"}}}}}}}]]; nested: QueryParsingException[[nested] failed to find nested object under path [campaignPurchases]];
openloyalty_elk | 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:853)
openloyalty_elk | 	at org.elasticsearch.search.SearchService.createContext(SearchService.java:652)
openloyalty_elk | 	at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
openloyalty_elk | 	at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:369)
openloyalty_elk | 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
openloyalty_elk | 	at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
openloyalty_elk | 	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
openloyalty_elk | 	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
openloyalty_elk | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
openloyalty_elk | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
openloyalty_elk | 	at java.lang.Thread.run(Thread.java:745)
openloyalty_elk | Caused by: [oloy.customer_details] QueryParsingException[[nested] failed to find nested object under path [campaignPurchases]]
openloyalty_elk | 	at org.elasticsearch.index.query.support.NestedInnerQueryParseSupport.setPath(NestedInnerQueryParseSupport.java:159)
openloyalty_elk | 	at org.elasticsearch.index.query.NestedQueryParser.parse(NestedQueryParser.java:82)
openloyalty_elk | 	at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
openloyalty_elk | 	at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:303)
openloyalty_elk | 	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:206)
openloyalty_elk | 	at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:201)
openloyalty_elk | 	at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
openloyalty_elk | 	at org.elasticsearch.search.SearchService.parseSource(SearchService.java:836)
openloyalty_elk | 	... 10 more
openloyalty_mail | [APIv1] KEEPALIVE /api/v1/events

**Comment by ditoargs2** [comment]
I got same problem here

**Comment by eligiable** [comment]
There is no proper documentation for this, there should be a proper guide to install this program, I'm struggling with OL for a month and no success yet.

- Getting the Same error as above,
- Emails are not Working.
- Password Request Forms are not Working.
- Domain Change leads to errors.

**Comment by ditoargs2** [comment]
my workaround:
1. prepare a very stable internet connection
2. delete container
3. delete all related images
4. pull source to another directory
5. rerun step from beginning

everything is working good now

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
