### ISSUE TITLE
"npm install" to new  server with old code.

### ISSUE THREAD

**Issue by arfeen** [DivanteLtd/open-loyalty#132]
I have a working environment on a server and working perfectly for 4 months already. Now I migrated the code to new server and run "npm install". Installed successfully and web pack successfully started against "npm start", but the result is that the Angular App is not rendering now. It only fetches the index file and executes nothing so overall the app does not work.

What is the reason behind this ? I already have a working instance and it runs fine. The same code to new server is not working. Is "npm install" creating problem in new server ? Any update is causing this breakage ?

I can't even copy the working "node_modules" directory as it does not work. What are my options here ?

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
