### ISSUE TITLE
Problem with Deploying in Docker-Windows 10 Environment

### ISSUE THREAD

**Issue by aazyzy** [DivanteLtd/open-loyalty#134]
Dear Director,

I tried to deploy the package with docker instruction you mentioned, but I get the following error after executing "docker-compose up" command in docker environment. I am running docker on windows 64bit.

`openloyalty_elk | [2018-11-19 13:30:02,919][DEBUG][action.search.type       ] [Agent Axis] [oloy.customer_details][0], node[nn7ZaekIRKGM-OL6Y6dP9Q], [P], v[4], s[STARTED], a[id=wRZUE-h7SiqSC3kgk5b_Yw]: Failed to execute [org.elasticsearch.action.search.SearchRequest@28190c43] lastShard [true]
openloyalty_elk | RemoteTransportException[[Agent Axis][172.18.0.2:9300][indices:data/read/search[phase/query]]]; nested: SearchParseException[failed to parse search source [{"query":{"nested":{"path":"campaignPurchases","query":{"bool":{"must":[{"match":{"campaignPurchases.status":"inactive"}}],"must_not":[{"match":{"campaignPurchases.used":true}}],"filter":{"exists":{"field":"campaignPurchases.activeSince"}}}}}}}]]; nested: QueryParsingException[[nested] failed to find nested object under path [campaignPurchases]];
openloyalty_elk | Caused by: SearchParseException[failed to parse search source [{"query":{"nested":{"path":"campaignPurchases","query":{"bool":{"must":[{"match":{"campaignPurchases.status":"inactive"}}],"must_not":[{"match":{"campaignPurchases.used":true}}],"filter":{"exists":{"field":"campaignPurchases.activeSince"}}}}}}}]]; nested: QueryParsingException[[nested] failed to find nested object under path [campaignPurchases]];
openloyalty_elk |       at org.elasticsearch.search.SearchService.parseSource(SearchService.java:853)
openloyalty_elk |       at org.elasticsearch.search.SearchService.createContext(SearchService.java:652)
openloyalty_elk |       at org.elasticsearch.search.SearchService.createAndPutContext(SearchService.java:618)
openloyalty_elk |       at org.elasticsearch.search.SearchService.executeQueryPhase(SearchService.java:369)
openloyalty_elk |       at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:368)
openloyalty_elk |       at org.elasticsearch.search.action.SearchServiceTransportAction$SearchQueryTransportHandler.messageReceived(SearchServiceTransportAction.java:365)
openloyalty_elk |       at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:350)
openloyalty_elk |       at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
openloyalty_elk |       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
openloyalty_elk |       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
openloyalty_elk |       at java.lang.Thread.run(Thread.java:745)
openloyalty_elk | Caused by: [oloy.customer_details] QueryParsingException[[nested] failed to find nested object under path [campaignPurchases]]
openloyalty_elk |       at org.elasticsearch.index.query.support.NestedInnerQueryParseSupport.setPath(NestedInnerQueryParseSupport.java:159)
openloyalty_elk |       at org.elasticsearch.index.query.NestedQueryParser.parse(NestedQueryParser.java:82)
openloyalty_elk |       at org.elasticsearch.index.query.QueryParseContext.parseInnerQuery(QueryParseContext.java:250)
openloyalty_elk |       at org.elasticsearch.index.query.IndexQueryParserService.innerParse(IndexQueryParserService.java:303)
openloyalty_elk |       at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:206)
openloyalty_elk |       at org.elasticsearch.index.query.IndexQueryParserService.parse(IndexQueryParserService.java:201)
openloyalty_elk |       at org.elasticsearch.search.query.QueryParseElement.parse(QueryParseElement.java:33)
openloyalty_elk |       at org.elasticsearch.search.SearchService.parseSource(SearchService.java:836)`

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
