### ISSUE TITLE
Issue NoConfigurationException

### ISSUE THREAD

**Issue by romainlaisne** [DivanteLtd/open-loyalty#138]
Hi,

Cloning the master branch and starting with docker, I get this error :

Fatal error: Uncaught Symfony\Component\Routing\Exception\NoConfigurationException in /var/www/openloyalty/var/cache/prod/appProdProjectContainerUrlMatcher.php:2744 Stack trace: #0 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/') #1 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component in /var/www/openloyalty/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 75

What should I do?
I have look at some previous issues containing this keywords, but there is not solutions provided.
I also tried Vagrant. Same result.

The login screen, at port 8182 looks like this. Seems to be missing some images and translations:
![image](https://user-images.githubusercontent.com/7721517/53284069-15407280-374f-11e9-9ab7-d4581a88c59f.png)

Thanks in advance!

**Comment by romainlaisne** [comment]
I just forgot to run the command "docker-compose -f docker/docker-compose.yml --user=www-data exec php phing setup".
It works now better, however, running the prod env, I miss the translation in the UI. Any ideas how I can solve this?

**Comment by romainlaisne** [comment]
I went to setting>Translations, edited the EN, saved. Now it works. Strange though, isn't it?

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
