### ISSUE TITLE
application loads very slow

### ISSUE THREAD

**Issue by exexzian** [DivanteLtd/open-loyalty#140]
Successfully setup docker version but why it takes so much time to load the login screen ? Also any subsequent changes on any page updates very slow.

**Comment by tjurczak** [comment]
Hi @exexzian,

It can be related with windows. Did you run OL on windows environment? Docker is supported by windows but sharing files between host and docker is slow.
Another problem can be enabled xdebug. Check if you have disabled xdebug before test application.

**Comment by exexzian** [comment]
@tjurczak  no i am using it on mac. By the way from where do I disable xdebug option?

**Comment by tjurczak** [comment]
@exexzian Unfortunately the same performance problem occures on Mac.

ad. xdebug. You described first solution. Second is disable all xdebug listeners like PhpStorm. But in you case performance problem is related with Mac and dockers. This is common problem a wide described on the internet.

**Comment by exexzian** [comment]
thanks @tjurczak  that pretty much sums up possibilities

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
