### ISSUE TITLE
Making changes in css template in the admin panel not reflecting on front-end.

### ISSUE THREAD

**Issue by aadilahlawat** [DivanteLtd/open-loyalty#143]
I'm trying to make changes in the admin panel option.
settings>configuration on this page under "css template" section. But changes are not reflecting on front-end.
I also tried making changes via ftp directly to some files, also not reflecting on front-end.
Please help me regarding this.

**Comment by aadilahlawat** [comment]
I'm trying to make changes in the admin panel option.
settings>configuration  on this page under "css template" section. But changes are not reflecting on front-end.
I also tried making changes via ftp directly to some files, also not reflecting on front-end.
Please help me regarding this.

**Comment by exexzian** [comment]
@aadilahlawat  you are making changes on files inside *frontend* folder or files inside docker container files-system ?

I made changes and it worked fine - though it required docker compose up --build

**Comment by aadilahlawat** [comment]
I tried the build but still no joy.
I also tried making changes in frontend\src\modules\admin.partials\templates\left-nav.html. Facing the same issue.

Am I doing anything wrong?

**Comment by exexzian** [comment]
if you running dev one than changes should reflect if not then try going into docker file system
`docker exec -i -t openloyalty_frontend /bin/bash`

and then make changes in html and css (remember these compiled version of files will have different structure than in `rontend\src\modules\admin.partials` )

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
