### ISSUE TITLE
Import huge xml data set

### ISSUE THREAD

**Issue by stanley87** [DivanteLtd/open-loyalty#144]
Hi team,
My side try to import huge dataset using import xml(few millions row),however seem like that long time to proceed with the import process and never end,any proper recommendation/solutions way to import existing customer xml set ?

**Comment by stanley87** [comment]
any update?

**Comment by exexzian** [comment]
did you tried customer xml import?

**Comment by cbksyol** [comment]
Hey @stanley87, please, write us an email on support@openloyalty.io so we could discuss it in details. Also, please, bear in mind that importing that big amount of data is something that the Enterprise Edition handles much better - OL Open Source is not quite optimized for such huge amounts.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
