### ISSUE TITLE
Open source version on Production project

### ISSUE THREAD

**Issue by essamsalah** [DivanteLtd/open-loyalty#148]
Hi,

Have anyone used the open-source version on a production grade project?

**Comment by exexzian** [comment]
yes, any specific issue you are facing ?

**Comment by colejarczyk** [comment]
@essamsalah are you facing any issues?

**Comment by manojudeshika93** [comment]
@colejarczyk how to log into the Admin Cockpit... I tried several times as guidelines. But, failed... 
can I know the steps to do that. thanks

**Comment by colejarczyk** [comment]
@manojudeshika93 could you share a screen with errors? I need more details to help you.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
