### ISSUE TITLE
Post install help

### ISSUE THREAD

**Issue by comeseecomesav** [DivanteLtd/open-loyalty#149]
I am new to programing and I am trying to set this system up for my family's small business. Upon finishing the install with docker on Ubuntu, the admin panel just keeps spinning. The login screen will flash then disappear. I have followed all of the steps from the install and everything appears to have been successful. I would appreciate your assistance.

**Comment by comeseecomesav** [comment]
For some reason, I cannot run the command "docker-compose -f docker/docker-compose.dev.yml exec --user=www-data php phing setup" It kicks back with a menu of options.

**Comment by comeseecomesav** [comment]
Im also getting this during the bootup "chmod: cannot access '/var/www/openloyalty/var/import': No such file or directory"

**Comment by colejarczyk** [comment]
@comeseecomesav 

Open Loyalty is quite advanced and rather for enterprise usage and if you're new to programming then I think it will be pretty hard for you to get it up & running. 

Please contact with kacper@openloyalty.io for a cloud version. I think it's a more suitable solution for you.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
