### ISSUE TITLE
Installation issues from Amazon EC2 machine deployment

### ISSUE THREAD

**Issue by rameshreddym** [DivanteLtd/open-loyalty#150]
We are trying to deploy it on amazon EC2 machine and installed docker on the machine. And also installed open loyalty using bellow commands

1. Go to the docker directory:
$ cd docker
2. Execute bellow command to run application:
$ docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
3. Then use another command to setup database, Elasticsearch and load some demo data:
$ docker-compose -f docker/docker-compose.yml exec --user=www-data php phing setup
4. Add host entry openloyalty.localhost as 127.0.0.1

But when we try to access 
1. Admin portal is not accessible http://openloyalty.localhost:8182
2. Customer portal is loading with api url issues http://openloyalty.localhost:8183
3. Merchant portal is not accessible http://openloyalty.localhost:8183

Please help us on this

**Comment by rameshreddym** [comment]
docker ps output
`CONTAINER ID        IMAGE                                      COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
d96476adbe88        divante/open-loyalty-web                   "nginx -g 'daemon of…"   22 minutes ago      Up 6 minutes        0.0.0.0:80->80/tcp, 0.0.0.0:8182->3001/tcp, 0.0.0.0:8183->3002/tcp, 0.0.0.0:8184->3003/tcp   open_loyalty_frontend
85eac700f49b        divante/open-loyalty-fpm                   "docker-php-entrypoi…"   22 minutes ago      Up 6 minutes        0.0.0.0:9000->9000/tcp                                                                       open_loyalty_backend
4a3abefdc1c7        mailhog/mailhog                            "MailHog"                22 minutes ago      Up 6 minutes        1025/tcp, 0.0.0.0:8186->8025/tcp                                                             open_loyalty_mail
6d9e0438f979        postgres:9                                 "docker-entrypoint.s…"   22 minutes ago      Up 6 minutes        0.0.0.0:5432->5432/tcp                                                                       open_loyalty_db
858ac987b768        divante/open-loyalty-elasticsearch:2.2.0   "/docker-entrypoint.…"   22 minutes ago      Up 6 minutes        0.0.0.0:9200->9200/tcp, 9300/tcp                                                             open_loyalty_elk
b66df6922a7c        docker_frontend                            "/bin/sh -c 'yarn in…"   40 minutes ago      Up 6 minutes        3000/tcp, 0.0.0.0:8081->8081/tcp                                                             open_loyalty_frontend_dev`

**Comment by rameshreddym** [comment]
Getting 404 from backend
![image](https://user-images.githubusercontent.com/21261625/63742639-10ec4200-c8b7-11e9-8987-39c0b47004ab.png)

**Comment by colejarczyk** [comment]
Hi @rameshreddym 

You can't use domain openloyalty.localhost. It's a domain that can be used only on local computer and accessible only from the same host. Well, it's localhost.

You need to attach & configure your own domain as stated in http://docs.openloyalty.io/en/latest/cookbook/how_to_change_domain.html

As for the API, do not use "/api" as there is nothing to do under this endpoint, go to the "/doc" to see Swagger or call an endpoint like "/api/customer". API reference is available here http://docs.openloyalty.io/en/latest/api/index.html

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
