### ISSUE TITLE
Transaction logs

### ISSUE THREAD

**Issue by od3n** [DivanteLtd/open-loyalty#151]
Where do we keep all transaction logs? In database?

**Comment by colejarczyk** [comment]
Hi @od3n 

What do you mean by transaction logs? Application logs or pushed customers transactions to the Open Loyalty?

As for logs, we keep them in var/log/*
As for customers transactions, check PostgreSQL and "events" table. Open Loyalty uses Event Sourcing so transactions are stored as events. Open Loyalty has two different storages, PostgreSQL as a write storage and Elasticsearch as a read storage. So you will find all transactions in Elasticsearch too, projected from PostgreSQL, in index oloy.transaction_details.

Hope that helps.

**Comment by od3n** [comment]
thank you for the reply, yeah thats the answer i'm looking.
