### ISSUE TITLE
Open Loyalty error with Docker-Compose using stink and vagrant in virtualbox

### ISSUE THREAD

**Issue by MarcioDuran** [DivanteLtd/open-loyalty#152]
Good morning everyone !!!

I'm starting now with Open Loyalty, I'm having problems with docker-compose:
The error follows:
**docker-compose version 1.24.1, build 4667896b**
[vagrant @ localhost ~] $ **docker-compose up**
ERROR:
         Can't find a suitable configuration file in this directory or any
         parent Are you in the right directory?
                                                                             
         Supported filenames: docker-compose.yml, docker-compose.yaml
                                                                             
What is happening ?

**Comment by colejarczyk** [comment]
Hi,

Docker can't find docker-compose.yml file because it doesn't exist in root directory, but in "docker" directory.

Either go to the "docker" directory or call "docker-compose -f docker/docker-compose.dev.yml up"

**Comment by MarcioDuran** [comment]
Hello, how are you !!! Colejarck
Now I came across another problem, which is no longer directory, which would be this problem, how to solve it.

See below:

[vagrant @ localhost open-loyalty] $ **docker-compose -f docker / docker-compose.yml up -d**

**ERROR: Couldn't connect to Docker daemon at http + docker: // localhost - is it running?**

**If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.**

Could you help me, Thanks !!!

**Comment by MarcioDuran** [comment]
Hello, how are you !!!* Cezary Olejarczyk *


Now I came across another problem, which is no longer directory, which
would be this problem, how to solve it.

See below:

[vagrant @ localhost open-loyalty] $ docker-compose -f docker /
docker-compose.yml up -d

ERROR: Couldn't connect to Docker daemon at http + docker: // localhost -
is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST
environment variable.

Could you help me, Thanks !!!

https://github.com/DivanteLtd/open-loyalty/issues/152



Em sex, 27 de set de 2019 às 07:33, Cezary Olejarczyk <
notifications@github.com> escreveu:

**Comment by colejarczyk** [comment]
Try to run this command with sudo. Possibly docker requires higher permissions.

**Comment by MarcioDuran** [comment]
Good afternoon, fine Cezary Olejarczyk !!!

I was able to access the files through the command: **sudo chown $ USER /var/run/docker.sock**
However when downloading the files, but for some reason that I do not know my notebook is not supporting the demand of downloaded files, I will try to resolve, otherwise I can talk to you again, thanks for responding.

Big hug,
Marcio Duran
Product Manager BuilderSite.com

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
