### ISSUE TITLE
I can't start Open Loyalty

### ISSUE THREAD

**Issue by sviacavaf** [DivanteLtd/open-loyalty#153]
Hello, I have reached open loyalty looking for similar software and this is the one that suits me, so I would like to try this software for a project (startup) that I want to achieve using this program.

I have followed all the steps as it says in Github, downloaded the repository, installed on a new (remote) machine with ubuntu server and installed docker-io then entered the docker folder and entered the docker-compose up command (configured the localhost as indicated with openloyalty.localhost), followed by this I had a series of errors such as: [link of pastebin](https://pastebin.com/aKC5N6i8})

Once I ran into these errors, it seemed I was missing 2 commands (which I thought were only for windows)

```
docker-compose -f docker / docker-compose.yml up -d
docker-compose -f docker / docker-compose.yml exec --user = www-data php phing setup
```

I made them and again I started with `docker-compose up`

and now throw this at me: [link of pastebin](https://pastebin.com/1MfeLmXB)

I try to enter the website (from outside since it is a remote server) and I try to enter with the IP: 8128/8183 / etc .. even without a port and does not access anything

**Comment by colejarczyk** [comment]
Take a look at https://github.com/DivanteLtd/open-loyalty/issues/147#issuecomment-544362674

Long story, short: by default Open Loyalty works at "openloyalty.localhost" which is not accessible as a remote URL because it's a "localhost". You must have a public available domain and configure Open Loyalty to use it. That domain must point to the remote server.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
