### ISSUE TITLE
db: forward host lookup failed: Unknown host

### ISSUE THREAD

**Issue by nirsnappy** [DivanteLtd/open-loyalty#154]
hi,
after running docker-compose up, i get this issue of Unknown host again and again, any suggestion ?

openloyalty_backend | db: forward host lookup failed: Unknown host
openloyalty_backend | ===> Waiting database on db:5432 ...

**Comment by colejarczyk** [comment]
Hi,

What system do you use on the host computer? Can you provide output of `docker-compose -f docker/docker-compose.dev.yaml ps`

Try to `docker-compose -f docker/docker-compose.dev.yaml down` to remove all containers and network. Then try to bring it up once again `docker-compose -f docker/docker-compose.dev.yaml up`

I guess it's something related to he networking.

**Comment by Sphinxs** [comment]
Have you fixed it @nirsnappy , I have already try what @colejarczyk has indicate, but nothing...

**Comment by colejarczyk** [comment]
@Sphinxs is that still on?

**Comment by Sphinxs** [comment]
I have fixed running `docker system prune`, thanks. [Reference](https://linuxize.com/post/how-to-remove-docker-images-containers-volumes-and-networks/).
