### ISSUE TITLE
Running Fail

### ISSUE THREAD

**Issue by dahaibao** [DivanteLtd/open-loyalty#155]
http://42.159.6.40:8183/#!/
I deployed the project in my cloud as the spec required. It seems it is working, but the landing page still can't be loaded.
What wrong with the issue? Is the hosts problem?

**Comment by colejarczyk** [comment]
if you deployed application on remote server then you have to configure domains, otherwise how the frontend app should know what is the url of API?

http://docs.openloyalty.io/en/stable/cookbook/how_to_change_domain.html

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
