### ISSUE TITLE
Kubernetes missing page

### ISSUE THREAD

**Issue by sultanmyrza** [DivanteLtd/open-loyalty#156]
If you go install in production http://docs.openloyalty.io/en/latest/developer/installation/installation.html#kubernetes section it is missing installation docs with kubernetes http://docs.openloyalty.io/en/latest/developer/installation/kubernetes.rst

**Comment by sultanmyrza** [comment]
Please provide Kubernetes page

**Comment by tjurczak** [comment]
@sultanmyrza Hi,

https://docs.openloyalty.io/en/latest/developer/installation/kubernetes.html

**Comment by sultanmyrza** [comment]
Thank you very much I think now this can be closed. 
I only engineer in a team so I'm learning Kubernetes complete beginner.
In docs it says 
> if you want to deploy Open Loyalty on AWS you have to adjust these scripts (Manifests etc)

If I'm using google cloud (GKE) should I change anything? 
Or I can just pull open-loyalty repo on gcloud  
continue from https://docs.openloyalty.io/en/latest/developer/installation/kubernetes.html#how-to-run-ol-on-minikube?

**Comment by sultanmyrza** [comment]
Oh by the way thank you @tjurczak
