### ISSUE TITLE
Earning rule is not showing

### ISSUE THREAD

**Issue by chengjk84** [DivanteLtd/open-loyalty#158]
I manually added 10 earning rules in admin but it is not showing up in admin panel under all earning rules, it is showing got 20+ rules at the bottom but not visible in the table. However, on client app it is showing on how to earn reward point... what happen?

**Comment by colejarczyk** [comment]
Without more details I can't tell you what happened.

Please provide at least application logs (var/logs/prod.log or var/logs/dev.log) and also a screen what is the response from the API

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
