### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by owxxxxxwo** [DivanteLtd/open-loyalty#16]
Hi, i installed win10 pro freshly, then docker version 17.03.1, and executed commands: docker-compose up & docker-compose exec backend phing setup, completely.

and i get this:
"Error 102 (net::ERR_CONNECTION_REFUSED): The server refused the connection."
 on 127.0.0.1:8182/ or 127.0.0.1:8183/.

Only the API documentation page on http://127.0.0.1:8181/doc does show up. What am i missing?

**Comment by colejarczyk** [comment]
Hi,

As far as I know, the Open Loyalty doesn't support installation on Windows using Docker. Please try with Vagrant.

**Comment by mkurzeja** [comment]
@owxxxxxwo as far as I know Docker for Windows is using a different IP
Usually something like 92.168.99.100

If 127.0.0.1 is the correct IP, please paste the result of running `docker-compose ps`

**Comment by owxxxxxwo** [comment]
The 92.168.99.100 does not work.

Here is the result of running docker-compose ps


         Name                        Command               State                 Ports
----------------------------------------------------------------------------------------------------
    open_loyalty_backend         docker-php-entrypoint /bin ...        Up             0.0.0.0:8181->80/tcp
    open_loyalty_elk                  /docker-entrypoint.sh elas ...   Up              9200/tcp, 9300/tcp
    open_loyalty_frontend        /bin/sh -c npm rebuild nod ...      Exit 1
    open_loyalty_mail                MailHog                           Up       1025/tcp, 0.0.0.0:8186->8025/tcp
    open_loyalty_postgresql      docker-entrypoint.sh postgres         Up              5432/tcp

**Comment by mkurzeja** [comment]
Your frontend container exited for some reason. Please paste the result (no more than last 100 lines) of running
`docker-compose logs frontend`

**Comment by owxxxxxwo** [comment]
Below is about the last 100 lines. Thanks your help for investigation, let me know if any further info required.

open_loyalty_frontend | Error in plugin 'sass'
open_loyalty_frontend | Message:
open_loyalty_frontend |     src/style/main.scss
open_loyalty_frontend | Error: File to import not found or unreadable: ../node_modules/foundation-sites/scss/foundation
open_loyalty_frontend |        Parent style sheet: /var/www/src/style/main.scss
open_loyalty_frontend |         on line 2 of src/style/main.scss
open_loyalty_frontend | >> @import "../node_modules/foundation-sites/scss/foundation";
open_loyalty_frontend |    ^
open_loyalty_frontend |
open_loyalty_frontend | [07:30:40] Finished 'sass' after 282 ms
open_loyalty_frontend | [07:30:42] Finished 'copyClientConfig' after 2.34 s
open_loyalty_frontend | [07:30:42] Finished 'copySellerConfig' after 2.33 s
open_loyalty_frontend | [07:30:42] Finished 'copyAdminConfig' after 2.92 s
open_loyalty_frontend | [07:30:42] Finished 'copyScripts' after 2.86 s
open_loyalty_frontend | [07:30:42] Starting 'copyAdminIndex'...
open_loyalty_frontend | [07:30:42] Starting 'copyClientIndex'...
open_loyalty_frontend | [07:30:42] Starting 'copySellerIndex'...
open_loyalty_frontend |
open_loyalty_frontend | events.js:154
open_loyalty_frontend |       throw er; // Unhandled 'error' event
open_loyalty_frontend |       ^
open_loyalty_frontend | Error: ENOTDIR: not a directory, stat '/var/www/src/node_modules/lodash'
open_loyalty_frontend |     at Error (native)
open_loyalty_frontend | npm info it worked if it ends with ok
open_loyalty_frontend | npm info using npm@3.8.6
open_loyalty_frontend | npm info using node@v5.12.0
open_loyalty_frontend | npm info readInstalled object
open_loyalty_frontend | npm info build /var/www/node_modules/node-sass
open_loyalty_frontend | npm info lifecycle node-sass@3.13.1~preinstall: node-sass@3.13.1
open_loyalty_frontend | npm info linkStuff node-sass@3.13.1
open_loyalty_frontend | npm info lifecycle node-sass@3.13.1~install: node-sass@3.13.1
open_loyalty_frontend |
open_loyalty_frontend | > node-sass@3.13.1 install /var/www/node_modules/node-sass
open_loyalty_frontend | > node scripts/install.js
open_loyalty_frontend |
open_loyalty_frontend | node-sass build Binary found at /var/www/node_modules/node-sass/vendor/linux-x64-47/binding.node
open_loyalty_frontend | npm info lifecycle node-sass@3.13.1~postinstall: node-sass@3.13.1
open_loyalty_frontend |
open_loyalty_frontend | > node-sass@3.13.1 postinstall /var/www/node_modules/node-sass
open_loyalty_frontend | > node scripts/build.js
open_loyalty_frontend |
open_loyalty_frontend | Binary found at /var/www/node_modules/node-sass/vendor/linux-x64-47/binding.node
open_loyalty_frontend | Testing binary
open_loyalty_frontend | Binary is fine
open_loyalty_frontend | node-sass@3.13.1 /var/www/node_modules/node-sass
open_loyalty_frontend | npm info ok
open_loyalty_frontend | yarn install v0.24.5
open_loyalty_frontend | [1/4] Resolving packages...
open_loyalty_frontend | success Already up-to-date.
open_loyalty_frontend | Done in 1.85s.
open_loyalty_frontend | [17:12:29] Requiring external module babel-register
open_loyalty_frontend | [17:12:34] Using gulpfile /var/www/Gulpfile.babel.js
open_loyalty_frontend | [17:12:34] Starting 'generateConfig'...
open_loyalty_frontend | [17:12:34] Configure local parameters
open_loyalty_frontend | [17:12:34] PROD flag detected, using defaults
open_loyalty_frontend | [17:12:34] Finished 'generateConfig' after 31 ms
open_loyalty_frontend | [17:12:34] Starting 'config'...
open_loyalty_frontend | [17:12:34] Finished 'config' after 34 ms
open_loyalty_frontend | [17:12:35] Requiring external module babel-register
open_loyalty_frontend | [17:12:35] Using gulpfile /var/www/Gulpfile.babel.js
open_loyalty_frontend | [17:12:35] Starting 'buildAdminModules'...
open_loyalty_frontend | [17:12:35] Starting 'copyAdminModulesTemplates'...
open_loyalty_frontend | [17:12:35] Starting 'copyAdminConfig'...
open_loyalty_frontend | [17:12:35] Starting 'buildClientModules'...
open_loyalty_frontend | [17:12:35] Starting 'copyClientModulesTemplates'...
open_loyalty_frontend | [17:12:35] Starting 'copyClientConfig'...
open_loyalty_frontend | [17:12:35] Starting 'buildSellerModules'...
open_loyalty_frontend | [17:12:35] Starting 'copySellerModulesTemplates'...
open_loyalty_frontend | [17:12:35] Starting 'copySellerConfig'...
open_loyalty_frontend | [17:12:35] Starting 'sass'...
open_loyalty_frontend | [17:12:35] Starting 'appAdmin'...
open_loyalty_frontend | [17:12:35] Starting 'copyTemplatesAdmin'...
open_loyalty_frontend | [17:12:35] Starting 'fonts'...
open_loyalty_frontend | [17:12:35] Starting 'img'...
open_loyalty_frontend | [17:12:35] Starting 'appCustomer'...
open_loyalty_frontend | [17:12:35] Starting 'copyTemplatesCustomer'...
open_loyalty_frontend | [17:12:35] Starting 'appSeller'...
open_loyalty_frontend | [17:12:35] Starting 'copyTemplatesSeller'...
open_loyalty_frontend | [17:12:35] Starting 'copyScripts'...
open_loyalty_frontend | Error in plugin 'sass'
open_loyalty_frontend | Message:
open_loyalty_frontend |     src/style/main.scss
open_loyalty_frontend | Error: File to import not found or unreadable: ../node_modules/foundation-sites/scss/foundation
open_loyalty_frontend |        Parent style sheet: /var/www/src/style/main.scss
open_loyalty_frontend |         on line 2 of src/style/main.scss
open_loyalty_frontend | >> @import "../node_modules/foundation-sites/scss/foundation";
open_loyalty_frontend |    ^
open_loyalty_frontend |
open_loyalty_frontend | [17:12:36] Finished 'sass' after 362 ms
open_loyalty_frontend | [17:12:37] Finished 'copyClientConfig' after 1.5 s
open_loyalty_frontend | [17:12:37] Finished 'copyAdminConfig' after 1.87 s
open_loyalty_frontend | [17:12:37] Finished 'copySellerConfig' after 1.85 s
open_loyalty_frontend | [17:12:37] Finished 'copyScripts' after 1.84 s
open_loyalty_frontend | [17:12:37] Starting 'copyAdminIndex'...
open_loyalty_frontend | [17:12:37] Starting 'copyClientIndex'...
open_loyalty_frontend | [17:12:37] Starting 'copySellerIndex'...
open_loyalty_frontend |
open_loyalty_frontend | events.js:154
open_loyalty_frontend |       throw er; // Unhandled 'error' event
open_loyalty_frontend |       ^
open_loyalty_frontend | Error: ENOTDIR: not a directory, stat '/var/www/src/node_modules/lodash'
open_loyalty_frontend |     at Error (native)

**Comment by lalitkt4** [comment]
hi open_loyalty_frontend is not working i got these errors:
open_loyalty_postgresql | ERROR:  relation "ol__settings" does not exist at character 210
open_loyalty_postgresql | STATEMENT:  SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.integer_value AS integer_value_3, t0.string_value AS string_value_4, t0.boolean_value AS boolean_value_5, t0.json_value AS json_value_6 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'integersettingentry', 'stringsettingentry', 'booleansettingentry', 'jsonsettingentry') LIMIT 1

**Comment by thomanh** [comment]
@lalitkt4 did you run: `docker-compose exec backend phing setup`

**Comment by usidoretheblue** [comment]
@owxxxxxwo  I am showing a very similar log output on my vagrant install as well.

All other containers are starting up and loading fine. This container does but then exits after it hangs on 

events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: ENOTDIR: not a directory, stat '/var/www/src/node_modules/lodash'
    at Error (native)

Sorry for just barging in on this thread but I am very interested in getting this up and running in a test environment to see if this can meet our needs.

Thanks!

**Comment by usidoretheblue** [comment]
hahahahahah well I guess it would help if I would read the dang README file in the Frontend directory.

Working on installing npm now.

Thanks!

**Comment by jokerywr** [comment]
Does anybody know the initial user/password of the backend admin?

**Comment by chadha** [comment]
@jokerywr 
run 
$ docker-compose exec backend phing setup
Then the default login is **admin** and password **open**. mentioned in  README.md

**Comment by lalitkt4** [comment]
I have successfully installed this in docker. but i m new in docker.
can you please suggest me how can i customise this application

**Comment by colejarczyk** [comment]
@lalitkt4 please run "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up"

Then you can just modify files in your favorite editor and see changes immediately.

**Comment by lalitkt4** [comment]
@colejarczyk from where we have to change in code? docker or clone directory after running 
"docker-compose -f docker-compose.yml -f docker-compose.dev.yml up" this
Thank you for help

**Comment by lalitkt4** [comment]
@colejarczyk  i have successfully installed open loyalty in docker. I couldn't find out from where i change code or do some customise in open loyalty.
i have install using this "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
cmd. Please suggest

**Comment by Lisota** [comment]
Hi, I had one problem while running ol_frontend image. I tryed to redownload your files from GitHub, but its the same. Is something bad with files from your side or its my problem? 
 
Error in plugin 'sass' 
Message: 
    src/style/main.scss 
Error: File to import not found or unreadable: ../node_modules/foundation-sites/scss/foundation 
       Parent style sheet: /var/www/src/style/main.scss 
        on line 2 of src/style/main.scss 
>> @import "../node_modules/foundation-sites/scss/foundation"; 
   ^ 
 
[13:40:10] Finished 'sass' after 181 ms 
[13:40:12] Finished 'copyClientConfig' after 1.94 s 
[13:40:12] Finished 'copySellerConfig' after 1.93 s 
[13:40:12] Finished 'copyAdminConfig' after 1.96 s 
[13:40:12] Finished 'copyScripts' after 1.91 s 
[13:40:12] Starting 'copyAdminIndex'... 
[13:40:12] Starting 'copyClientIndex'... 
[13:40:12] Starting 'copySellerIndex'... 
 
events.js:154 
      throw er; // Unhandled 'error' event 
      ^ 
Error: ENOTDIR: not a directory, stat '/var/www/src/node_modules/lodash' 
 
 
while running ol_frontend image.

**Comment by tjurczak** [comment]
@Lisota 
Error message:
> not a directory, stat '/var/www/src/node_modules/lodash
is related to incompatibility Windows filesystem and docker sharing volumens. Npm try to install module using symlink which are not supported in Windows.

I suppose you have Windows system, so:
If you would like to see working system without any development, please try:
`docker-compose up`
otherwise if you would like to make some changes in source code, you have to use docker on vagrant and then call:
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up`

**Comment by lalitkt4** [comment]
[Doctrine\DBAL\Exception\SyntaxErrorException]                                                                                              
  An exception occurred while executing 'INSERT INTO ol__email (email_id, key, subject, content, sender_name, sender_email, updated_at) VALU  
  ES (?, ?, ?, ?, ?, ?, ?)' with params ["a6538cec-7d42-45a6-93dc-336e36ba0ea7", "OpenLoyaltyUserBundle:email:registration.html.twig", "Acco  
  unt created", "<!DOCTYPE html PUBLIC \"-\/\/W3C\/\/DTD XHTML 1.0 Transitional\/\/EN\"\"http:\/\/www.w3.org\/TR\/xhtml1\/DTD\/xhtml1-transi  
  tional.dtd\">\n<html xmlns=\"http:\/\/www.w3.org\/1999\/xhtml\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" conten  
  t=\"width=device-width\">\n    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n    <title><\/title>\n\n    <!-- Web Font \/ @fo  
  nt-face : BEGIN -->\n\n    <!--[if mso]>\n    <style>\n        * {\n            font-family: sans-serif !important;\n        }\n    <\/sty  
  le>\n    <![endif]-->\n\n    <!--[if !mso]><!-->\n    <!-- insert web font reference, eg: <link href='https:\/\/fonts.googleapis.com\/css?  
  family=Roboto:400,700' rel='stylesheet' type='text\/css'> -->\n    <!--<![endif]-->\n\n    <!-- Web Font \/ @font-face : END -->\n\n    <s  
  tyle type=\"text\/css\">\n\n\n        html,\n        body {\n            margin: 0 auto !important;\n            padding: 0 !important;\n   
             height: 100% !important;\n            width: 100% !important;\n        }\n\n        * {\n            -ms-text-size-adjust: 100%  
  ;\n            -webkit-text-size-adjust: 100%;\n        }\n\n        div[style*=\"margin: 16px 0\"] {\n            margin: 0 !important;\n  
          }\n\n        table,\n        td {\n            mso-table-lspace: 0pt !important;\n            mso-table-rspace: 0pt !important;\n   
         }\n\n        table {\n            border-spacing: 0 !important;\n            border-collapse: collapse !important;\n            tab  
  le-layout: fixed !important;\n            Margin: 0 auto !important;\n        }\n\n        table table table {\n            table-layout:   
  auto;\n        }\n\n        img {\n            -ms-interpolation-mode: bicubic;\n        }\n\n        .mobile-link--footer a,\n        a[x  
  -apple-data-detectors] {\n            color: inherit !important;\n            text-decoration: underline !important;\n        }\n\n    <\/  
  style>\n\n    <style>\n\n        .button-td,\n        .button-a {\n            transition: all 100ms ease-in;\n        }\n\n        .butto  
  n-td:hover,\n        .button-a:hover {\n            background: #2e8ab8 !important;\n            border-color: #2e8ab8 !important;\n        
    }\n\n        @media screen and (max-width: 100%px) {\n\n            .email-container {\n                width: 100% !important;\n         
           margin: auto !important;\n            }\n\n            .fluid,\n            .fluid-centered {\n                max-width: 100% !i  
  mportant;\n                height: auto !important;\n                Margin-left: auto !important;\n                Margin-right: auto !im  
  portant;\n            }\n\n            .fluid-centered {\n                Margin-left: auto !important;\n                Margin-right: aut  
  o !important;\n            }\n\n            .stack-column,\n            .stack-column-center {\n                display: block !important;  
  \n                width: 100% !important;\n                max-width: 100% !important;\n                direction: ltr !important;\n        
        }\n\n            .stack-column-center {\n                text-align: left !important;\n            }\n\n            .center-on-narro  
  w {\n                text-align: left !important;\n                display: block !important;\n                Margin-left: auto !importan  
  t;\n                Margin-right: auto !important;\n                float: none !important;\n            }\n\n            table.center-on-  
  narrow {\n                display: inline-block !important;\n            }\n\n        }\n\n    <\/style>\n\n<\/head>\n<body bgcolor=\"#f9f  
  9f9\" width=\"100%\" style=\"Margin: 0;\">\n<div style=\"width: 100%; background: #f9f9f9;\">\n\n    <table cellspacing=\"0\" cellpadding=  
  \"0\" border=\"0\"  align=\"center\"  style=\"margin: auto;\"\n           class=\"email-container\">\n        <tr>\n            <td style=  
  \"padding: 20px 0; text-align: center; font-family: sans-serif; font-size: 35px; mso-height-rule: exactly; line-height: 80px; font-weight:  
   bold;\">\n                <b>OpenLoyalty<\/b>\n            <\/td>\n        <\/tr>\n    <\/table>\n\n    <table border=\"0\" bordercolor=\  
  "#e4e4e4\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\" bgcolor=\"#ffffff\" width=\"100%\" style=\"max-width: 600px; margin: auto;  
   border: 1px solid #e4e4e4\"\n           class=\"email-container\">\n\n        <tr>\n            <td style=\"padding-left: 40px; padding-b  
  ottom: 0px; padding-top: 40px;  text-align: left; font-family: sans-serif; font-size: 30px; mso-height-rule: exactly; line-height: 30px; c  
  olor: #555555;\">\n                Activate account\n            <\/td>\n        <\/tr>\n\n        <tr>\n            <td style=\"padding-l  
  eft: 40px; padding-bottom: 20px; padding-top: 40px; padding-right: 40px;  text-align: left; font-family: sans-serif; font-size: 15px; mso-  
  height-rule: exactly; line-height: 20px; color: #555555;\">\n                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Susp  
  endisse fermentum laoreet ornare. Nunc\n                sagittis scelerisque tempus. Nunc vitae orci quis metus tincidunt venenatis id et   
  quam&nbsp;erat.\n            <\/td>\n        <\/tr>\n        <tr>\n\n            <td style=\"padding-left: 40px;padding-right: 40px; paddi  
  ng-bottom: 40px; padding-top: 20px; text-align: center; font-family: sans-serif; font-size: 15px; mso-height-rule: exactly; line-height: 2  
  0px; color: #555555;\">\n                <table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" align=\"left\" style=\"Margin: auto\">\n   
                     <tr>\n                        <td style=\"background: #3399cc; text-align: left;\" class=\"button-td\">\n                
                <a href=\"{{ url }}\"\n                               style=\"background: #3399cc; border: 15px solid #3399cc; font-family:   
  sans-serif; font-size: 13px; line-height: 1.1; text-align: center; text-decoration: none; display: block; border-radius: 3px; font-weight:  
   bold;\"\n                               class=\"button-a\">\n                                &nbsp;&nbsp;&nbsp;&nbsp;<span style=\"color:  
  #ffffff\">ACTIVATE ACCOUNT<\/span>&nbsp;&nbsp;&nbsp;&nbsp;\n                            <\/a>\n                        <\/td>\n             
           <\/tr>\n                <\/table>\n            <\/td>\n        <\/tr>\n\n\n    <\/table>\n\n    <table cellspacing=\"0\" cellpadd  
  ing=\"0\" border=\"0\" align=\"center\" width=\"100%\" style=\"margin: auto;\"\n           class=\"email-container\">\n        <tr>\n       
         <td style=\"padding: 40px 10px;width: 100%;font-size: 12px; font-family: sans-serif; mso-height-rule: exactly; line-height:18px; te  
  xt-align: center; color: #888888;\">\n                Lorem ipsum dolor sit amet, consectetur adipiscing elit.<br>\n                Suspen  
  disse fermentum laoreet ornare.<br><br>\n\n                Nunc sagittis scelerisque tempus. Nunc vitae orci quis metus<br>\n               
     tincidunt venenatis id et quam.<br>\n                <br><br>\n            <\/td>\n        <\/tr>\n    <\/table>\n\n<\/div>\n<\/body>\n  
  <\/html>\n", "Lalit", "lalitk@techfoursolutions.com", "2017-09-07 15:08:37"]:                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your My  
  SQL server version for the right syntax to use near 'key, subject, content, sender_name, sender_email, updated_at) VALUES ('a6538cec-' at   
  line 1                                                                                                                                      
                                                                                                                                              

                                                                                                                                              
  [Doctrine\DBAL\Driver\PDOException]                                                                                                         
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your My  
  SQL server version for the right syntax to use near 'key, subject, content, sender_name, sender_email, updated_at) VALUES ('a6538cec-' at   
  line 1                                                                                                                                      
                                                                                                                                              

                                                                                                                                              
  [PDOException]                                                                                                                              
  SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your My  
  SQL server version for the right syntax to use near 'key, subject, content, sender_name, sender_email, updated_at) VALUES ('a6538cec-' at   
  line 1                                                                                                                                      
                                                                                                                                              

doctrine:fixtures:load [--fixtures [FIXTURES]] [--append] [--em EM] [--shard SHARD] [--purge-with-truncate] [--multiple-transactions] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by colejarczyk** [comment]
@lalitkt4 in case of assistance in the installation of the Open Loyalty, I suggest contacting our support and maintenance team via support@openloyalty.io. Our core product team covers only issues connected with improving the product or developing new features.

**Comment by Lisota** [comment]
We change windows to pro version and the same problem 


Error in plugin 'sass'
Message:
src/style/main.scss
Error: File to import not found or unreadable: ../node_modules/foundation-sites/scss/foundation
Parent style sheet: /var/www/src/style/main.scss
on line 2 of src/style/main.scss

        @import "../node_modules/foundation-sites/scss/foundation";
        ^

[13:40:10] Finished 'sass' after 181 ms
[13:40:12] Finished 'copyClientConfig' after 1.94 s
[13:40:12] Finished 'copySellerConfig' after 1.93 s
[13:40:12] Finished 'copyAdminConfig' after 1.96 s
[13:40:12] Finished 'copyScripts' after 1.91 s
[13:40:12] Starting 'copyAdminIndex'...
[13:40:12] Starting 'copyClientIndex'...
[13:40:12] Starting 'copySellerIndex'...

events.js:154
throw er; // Unhandled 'error' event
^
Error: ENOTDIR: not a directory, stat '/var/www/src/node_modules/lodash'

while running ol_frontend image.
