### ISSUE TITLE
Install in remote server?

### ISSUE THREAD

**Issue by marcelodelta** [DivanteLtd/open-loyalty#162]
We are testing the platform. How to install on a remote server?

Congratulations on the project.

**Comment by colejarczyk** [comment]
What do you mean by remote server ? A bare plate machine of yours? A cloud provider server? AWS / GCloud? 

I strongly recommend to use Kubernetes. 

https://docs.openloyalty.io/en/latest/developer/installation/kubernetes.html

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
