### ISSUE TITLE
Website not running

### ISSUE THREAD

**Issue by jiripaskov** [DivanteLtd/open-loyalty#164]
Hello boys. Your website https://www.openloyalty.io/ is not running. I would like to check some demo and can´t. Thanks.

**Comment by MrHubert** [comment]
Dear Jiripaskov, can you try to access the website again? It seems like it's working completely fine on our end.

If you'd like to schedule a demo of Open Loyalty, simply fill in the form, and we'll get in touch with you.

**Comment by colejarczyk** [comment]
Closing due long time without response. If the problem still occurs, please reopen this issue.
