### ISSUE TITLE
ERROR: Service 'php' failed to build: pull access denied for composer/composer, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by bboz** [DivanteLtd/open-loyalty#167]
I was try to install open loyality development enviroment but I got error and I dont know how to fix it. 
My operating system is windows 10 and I follow this doc: https://docs.openloyalty.io/en/3.2.0/developer/installation/installation.html
![Ekran Alıntısı](https://user-images.githubusercontent.com/15327911/75514160-d8fdbd00-5a07-11ea-9e4e-d16d2e82833e.PNG)

**Comment by colejarczyk** [comment]
Hi @bboz 

I've applied some fixes to docker files. Please try once again after pulling the latest changes.

Best,
Cezary

**Comment by bboz** [comment]
> Hi @bboz
> 
> I've applied some fixes to docker files. Please try once again after pulling the latest changes.
> 
> Best,
> Cezary

Thanks, I will try.

**Comment by bboz** [comment]
> > Hi @bboz
> > I've applied some fixes to docker files. Please try once again after pulling the latest changes.
> > Best,
> > Cezary
> 
> Thanks, I will try.

@colejarczyk 
It worked flawlessly.
Thanks.
