### ISSUE TITLE
How can I reach to all data?

### ISSUE THREAD

**Issue by nejatian** [DivanteLtd/open-loyalty#169]
I have noticed that some basic data for user creation like birthdate and loyalty card numbers don't store in the database!
how can I reach them?

**Comment by pawelabrams** [comment]
Many details on the user, their points and transactions are saved as events to allow for easy rebuilding of any state in the past; therefore, the data is stored in `events` table, but not that easy to get out of.

To access these easily, a current copy of data (called a projection) is stored in ElasticSearch. You can see the projections by accessing ES data, for example using this chrome extension: https://chrome.google.com/webstore/detail/elasticsearch-head/ffmkiejjmecolpfloofpjologoblkegm

The address of the ES cluster in dev mode is http://localhost:9200/ (you need to get it into the field in the extension, not in the address bar of your browser).

To read more about getting data out of the OL's store, visit our docs ( https://docs.openloyalty.io/en/3.2.0/ ) and see the API page of your installation (f.e. http://openloyalty.localhost/doc ). I promise the API is much more friendly than getting raw data out of ES (and this ES representation might change between versions while the API stays relatively the same or backwards-compatible).

**Comment by nejatian** [comment]
Thank you for responding.
