### ISSUE TITLE
ERROR: Service 'php' failed to build: pull access denied for openloyalty/base-php-fpm, repository does not exist or may require 'docker login': denied: requested access to the resource is denied

### ISSUE THREAD

**Issue by kname97** [DivanteLtd/open-loyalty#170]
![image](https://user-images.githubusercontent.com/53926205/76486410-d5c7ef80-6451-11ea-81f6-ae915419ad0e.png)

**Comment by colejarczyk** [comment]
Hi @kname97 

run `./docker/base/build_dev.sh` in the first place before `docker-compose -f docker/docker-compose.dev.yml up`

**Comment by kname97** [comment]
thank for help @colejarczyk , but it till error, pls help me. thanks 
![image](https://user-images.githubusercontent.com/53926205/76501192-68798600-6474-11ea-98ab-742192a529d1.png)

**Comment by colejarczyk** [comment]
@kname97 

Have you opened or changed any files once you cloned the repository?

**Comment by kname97** [comment]
no. I just followed the instructions from README.md

**Comment by colejarczyk** [comment]
@kname97 

So I guess it's related to the files encoding and differences between Windows and Linux. Windows uses "\r\n" chars as a marker of the end of line whereas Unix/Linux uses "\n". I guess this is a reason for your error.

Please try to run it on Linux env or use Vagrant instead.

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.

**Comment by nmt0504** [comment]
Hi @colejarczyk, i have the same issue here, I run ./docker/base/build_dev.sh first, after I run docker-compose -f docker/docker-compose.dev.yml up, but I received an error "ERROR: Service 'frontend' failed to build : pull access denied for openloyalty/base-nodejs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied". Please help me on it.

**Comment by nguyen123** [comment]
@colejarczyk  @nmt0504  @kname97 
I still error same as : 
I run ./docker/base/build_dev.sh first, after I run docker-compose -f docker/docker-compose.dev.yml up, but I received an error "ERROR: Service 'frontend' failed to build : pull access denied for openloyalty/base-nodejs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied". Please help me on it.

please help me. thanks
