### ISSUE TITLE
Basic Local Setup Error

### ISSUE THREAD

**Issue by UnderFenex** [DivanteLtd/open-loyalty#172]
Hi, when I run: docker-compose up. I get this error in local and production. Any hints?

Fatal error: Uncaught Symfony\Component\Routing\Exception\NoConfigurationException in /var/www/openloyalty/var/cache/prod/appProdProjectContainerUrlMatcher.php:2744 Stack trace: #0 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/Routing/Matcher/UrlMatcher.php(95): appProdProjectContainerUrlMatcher->match('/') #1 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/Routing/Router.php(262): Symfony\Component\Routing\Matcher\UrlMatcher->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #2 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/EventListener/RouterListener.php(115): Symfony\Component\Routing\Router->matchRequest(Object(Symfony\Component\HttpFoundation\Request)) #3 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php(212): Symfony\Component\HttpKernel\EventListener\RouterListener->onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent), 'kernel.request', Object(Symfony\Component in /var/www/openloyalty/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php on line 75

**Comment by UnderFenex** [comment]
I managed to solve the previous issue, but now, I have this one

![image](https://user-images.githubusercontent.com/3832413/77460203-cb511280-6dce-11ea-8a86-10da55dc36e0.png)

**Comment by UnderFenex** [comment]
I've managed to solve the previous issue, but now, I have this one

![image](https://user-images.githubusercontent.com/3832413/77460414-081d0980-6dcf-11ea-86f0-31b7adb6d298.png)

**Comment by pawelabrams** [comment]
Your second issue is a problem with Cross-Origin Resource Sharing. Use the tips from the following comment to fix it. https://github.com/DivanteLtd/open-loyalty/issues/166#issuecomment-590344115

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.
