### ISSUE TITLE
Setup SSL

### ISSUE THREAD

**Issue by UnderFenex** [DivanteLtd/open-loyalty#173]
How can I setup the SSL for the different ports, as they contain mixed content.

**Comment by pawelabrams** [comment]
It should be enough to set up the SSL only in the nginx (4 servers, 2 files total):
https://github.com/DivanteLtd/open-loyalty/blob/master/docker/prod/web/backend.conf
https://github.com/DivanteLtd/open-loyalty/blob/master/docker/prod/web/frontend.conf

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.
