### ISSUE TITLE
Connecting to Elasticsearch

### ISSUE THREAD

**Issue by KhatereTajfar** [DivanteLtd/open-loyalty#174]
I'm trying to write REST API and send requests directly to **elk container** however, I'm struggling to change the **transport.host** Ip address. is it posible to make changes to the config file of elasticsearch? if so, how can I do this?

**Comment by pawelabrams** [comment]
We currently support retrieving data from Elasticsearch only through PHP-based REST API. You can find the documentation on your development server, on http://openloyalty.localhost/doc endpoint.

If you want to extend the abilities of the API, you will need to edit the code in backend directory.

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.
