### ISSUE TITLE
backup elasticsearch

### ISSUE THREAD

**Issue by KhatereTajfar** [DivanteLtd/open-loyalty#175]
I successfully managed to back up the open loyalty cluster and now I want to restore it on my server (with elasticsearch 5.0.0) but I only have access to the backups folder provided that I run the `docker exec -it open_loyalty_elk bash` command in terminal. I mean otherwise, the backup folder is not visible. How can I restore all elasticsearch data on my server?

**Comment by pawelabrams** [comment]
Unless there was a modification of the system, data stored in Elasticsearch is not needed to move data to the production server, it is a reflection of what is stored in database.

To repopulate elasticsearch cluster on the production server, after you restore your database, log into the `php` container and run

```
bin/console oloy:user:projections:index:create --drop-old
bin/console oloy:utility:read-models:recreate
```

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.
