### ISSUE TITLE
adding translations broke admin panel, admin panel stop working after adding this translation, but customer panel and merchant panel are working fine

### ISSUE THREAD

**Issue by sultanmyrza** [DivanteLtd/open-loyalty#177]
adding translations broke admin panel, 
after adding OpenLoyalty_English.json translation, 
https://gist.github.com/sultanmyrza/3829fdd92c88460929f235272853c149
admin panel stop working, but customer panel and merchant panel are working fine

by the way, JSON is valid
https://imgur.com/CsafrxJ

some logs from docker-compose up after adding translations
```
openloyalty_db | ERROR:  relation "ol__settings" does not exist at character 241
openloyalty_db | STATEMENT:  SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.boolean_value AS boolean_value_3, t0.json_value AS json_value_4, t0.integer_value AS integer_value_5, t0.json_value AS json_value_6, t0.string_value AS string_value_7 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'booleansettingentry', 'jsonsettingentry', 'integersettingentry', 'filesettingentry', 'stringsettingentry') LIMIT 1
openloyalty_db | ERROR:  relation "ol__settings" does not exist at character 241
openloyalty_db | STATEMENT:  SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.boolean_value AS boolean_value_3, t0.json_value AS json_value_4, t0.integer_value AS integer_value_5, t0.json_value AS json_value_6, t0.string_value AS string_value_7 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'booleansettingentry', 'jsonsettingentry', 'integersettingentry', 'filesettingentry', 'stringsettingentry') LIMIT 1
openloyalty_db | ERROR:  relation "ol__segment" does not exist at character 196
openloyalty_db | STATEMENT:  SELECT o0_.segment_id AS segment_id_0, o0_.name AS name_1, o0_.description AS description_2, o0_.active AS active_3, o0_.customers_count AS customers_count_4, o0_.created_at AS created_at_5 FROM ol__segment o0_ WHERE o0_.active = $1
```

**Comment by pawelabrams** [comment]
As far as I know, the JSON file you provided is not in a format that is recognized anywhere in OpenLoyalty. How did you add the file into the system?

The errors you provided are a sign of either PostgreSQL that stopped working or a corrupted database. Please check `docker ps` to see if `db` container is running or has exited.

If `db` container is running, some other action you performed may have damaged the database. You can use `psql` command in `db` container to access database and see if the tables are still in there. 

Some of the actions that may have resulted in these errors include removing docker volumes, running phing setup / phing basic-setup and exiting in the process, manual changes in database.

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.
