### ISSUE TITLE
How to change CSS (SASS)?

### ISSUE THREAD

**Issue by jPedroScript** [DivanteLtd/open-loyalty#178]
Hello,

I am having difficulty changing the CSS. I have tried two modes, but have not been able to get it so far.

Problems detected:

1. I have added CSS classes in the "CSS Template" section in Settings. But the changes are not reflected.

![Screenshot_194](https://user-images.githubusercontent.com/1754671/78570041-0cdbb780-77ea-11ea-8fbb-715e1b836641.png)

2. I have modified SASS files in the "frontend \ src \ style" folder. How can I compile them? I see the final CSS file is called commons.bundle.css (path: site.com:8182/assets/styles/commons.bundle.css). How can I generate a new commons.bundle.css file from the modified SASS?

![Screenshot_195](https://user-images.githubusercontent.com/1754671/78570228-51675300-77ea-11ea-8f2c-3bdc4d1a3993.png)

Please appreciate your support.
Greetings.

**Comment by pawelabrams** [comment]
Hey @jPedroScript !

The CSS field in the admin panel is supposed to be accessed by client panel applications and does not affect admin panel.

If you use docker-compose.dev.yml file while setting up your developer environment, the compilation is done every time the files change while the frontend docker container is running.

If you don't want docker container to be running for some reason, the frontend/README file contains instructions on how to run an instance locally. Node-sass compilation is run by the main process of the application on start.

**Comment by colejarczyk** [comment]
Closing due a long time without response. If the problem still occurs, please reopen this issue.
