### ISSUE TITLE
ERROR: Service 'frontend' failed to build

### ISSUE THREAD

**Issue by marcoadasilvaa** [DivanteLtd/open-loyalty#180]
Reference dev/front-dockerfile

FROM openloyalty/base-nodejs AS front

RUN

```
docker-compose -f docker/docker-compose.dev.yml up --build
```

Result:

```
Building frontend
Step 1/6 : FROM openloyalty/base-nodejs AS front
ERROR: Service 'frontend' failed to build: pull access denied for openloyalty/base-nodejs, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Maybe fix?

Remplace FROM openloyalty/base-nodejs AS front to FROM divante/open-loyalty-base-nodejs

**Comment by colejarczyk** [comment]
please read README.md, especially https://github.com/DivanteLtd/open-loyalty#for-developers

**Comment by marcoadasilvaa** [comment]
Thank you! it ok for me!
