### ISSUE TITLE
RabbitMQ Management

### ISSUE THREAD

**Issue by KhatereTajfar** [DivanteLtd/open-loyalty#182]
I used this command `docker-compose -f docker-compose.dev.yml up` to run docker. Following this link https://docs.openloyalty.io/en/stable/developer/environment/rabbitmq.html#rabbitmq-management I don't have access to  http://localhost:8672 . I guess this port has not been set in `docker-compose.dev.yml` file.

**Comment by colejarczyk** [comment]
Hi @KhatereTajfar 

RabbitMQ and queues are not available in Open Source edition, only in Enterprise Edition. The documentation describes both editions but some of the features like queues are not available in OS.
