### ISSUE TITLE
Permission Denied to RUN yarn install

### ISSUE THREAD

**Issue by veeresh-sd** [DivanteLtd/open-loyalty#187]
Running docker on github action workflow, the issue with yarn installation.

Any Idea on this?

`Step 6/11 : RUN apk add --no-cache git
 ---> Running in 3af91b03d6b0
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/6) Installing ca-certificates (20190108-r0)
(2/6) Installing libssh2 (1.9.0-r1)
(3/6) Installing libcurl (7.61.1-r3)
(4/6) Installing expat (2.2.8-r0)
(5/6) Installing pcre2 (10.30-r0)
(6/6) Installing git (2.15.4-r0)
Executing busybox-1.27.2-r7.trigger
Executing ca-certificates-20190108-r0.trigger
OK: 29 MiB in 25 packages
Removing intermediate container 3af91b03d6b0
 ---> 77bcdac867f3
Step 7/11 : RUN npm install -g yarn
 ---> Running in d09dc438588b
/usr/local/bin/yarnpkg -> /usr/local/lib/node_modules/yarn/bin/yarn.js
/usr/local/bin/yarn -> /usr/local/lib/node_modules/yarn/bin/yarn.js
+ yarn@1.22.4
added 1 package in 0.51s
Removing intermediate container d09dc438588b
 ---> 5a7bd9826815
Step 8/11 : RUN yarn install
 ---> Running in 5a3b81b72f77
/bin/sh: yarn: Permission denied
The command '/bin/sh -c yarn install' returned a non-zero code: 126`

**Comment by colejarczyk** [comment]
what command is causing this issue?
have you pulled the latest changes?

**Comment by veeresh-sd** [comment]
I have fixed it from my end. Thank you.

**Comment by crocco95** [comment]
Hi, can someone share how to solve the problem ? I have a very similar/the same issue.
It's this one #191

**Comment by colejarczyk** [comment]
I guess you need to remove line "bin/sh -c yarn install" from docker image s as base docker changed and includes yarn already
