### ISSUE TITLE
[Fork] Create Maintain Version of Opensource Distribution 

### ISSUE THREAD

**Issue by ad3n** [DivanteLtd/open-loyalty#189]
I read the LICENSE and i found this software use MIT License, probably the Framework. But in framework i can't found the license file

I just fork this software and try to upgrading to support Symfony 5.1 (latest version)

I create this issue just to inform you about my work and get the permission from you also

Thanks,

Regards,

Surya Ihsan

**Comment by colejarczyk** [comment]
Hi @ad3n 

Both repositories are under the same licence 
- https://github.com/DivanteLtd/open-loyalty/blob/master/LICENSE
- https://github.com/DivanteLtd/open-loyalty-framework/blob/master/LICENSE

**Comment by ad3n** [comment]
@colejarczyk Thank you very much for your confirmation
