### ISSUE TITLE
Forever loading screen on "Add Earning Points Rule" or "Edit Earning Points Rule"

### ISSUE THREAD

**Issue by chwong1** [DivanteLtd/open-loyalty#19]
When I click into "Add Earning Points Rule", the loading keeps forever.

![screen shot 2017-06-21 at 11 41 34 am](https://user-images.githubusercontent.com/8508730/27366110-9e44d92e-5676-11e7-9738-efa1a5550069.png)

**Comment by colejarczyk** [comment]
Hi,

@chwong1 check our latest release 1.2
