### ISSUE TITLE
Yarn strange error

### ISSUE THREAD

**Issue by crocco95** [DivanteLtd/open-loyalty#191]
Hi, when I try to launch Open Loyalty on my dedicated server, the container "open_loyalty_frontend_dev" throws the screenshot's exceptions.
In my local environment on Mac OS, docker compile well and there aren't errors.

I want to test the community version before to buy the license and I need to install this on server because in local environment is slow and sloppy af.

<img width="1114" alt="Schermata 2020-07-28 alle 19 24 58" src="https://user-images.githubusercontent.com/6146017/88700313-cdbed280-d108-11ea-9c60-bc95a2fad293.png">

**Comment by colejarczyk** [comment]
how you started Open Loyalty? can you share a command?

**Comment by crocco95** [comment]
The issue was not related to the startup command but to node js modules, I have solved now so I close the issue.
