### ISSUE TITLE
Sample data keeps getting truncated

### ISSUE THREAD

**Issue by aolee** [DivanteLtd/open-loyalty#202]
Hi everyone,

In dev mode, is there any cron'ed script that keeps flushing the DB? it happens in random. not sure what's the cause, every time it happens , I always execute ...

"docker-compose -f docker/docker-compose.dev.yml exec --user=www-data php phing setup"

to make the dev env, work again.

I've deployed the docker version in Digital Ocean, not on local machine

![image](https://user-images.githubusercontent.com/700718/108154085-4cb44080-7117-11eb-93b5-bcd1491f172b.png)

**Comment by pradeepKsrvastva** [comment]
@aolee Can you please give me your docker-compose.yml file i am a bit stuck at it i would be very glad thanks

**Comment by colejarczyk** [comment]
@aolee just take a look at what "phing setup" does and it will be crystal clear. It's clears data and then uploads a sample data

**Comment by aolee** [comment]
Hi @colejarczyk thanks for your reply. after having a closer look, somehow it elasticsearch data is truncated randomly, I have visited Postgres and all data is there. not sure what's causing elasticsearch data to get cleared, but after I modified the docker dev file to use Volume for both Postgres and elasticsearch, it never happened anymore. Good learning for me :)

**Comment by aolee** [comment]
Closing the issue for now :)
