### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by fareedpatel** [DivanteLtd/open-loyalty#24]
Please, could you provide the URL so I can find the full documentation for the API?

**Comment by gujiman** [comment]
if you install locally:

8182 - the administration panel,

8183 - the customer panel,

8184 - the merchant panel,

8181 - RESTful API port

but if your using open-loyalty demo then it would be great if someone could provide the url for the RESTful API in the demo, i.e something like

http://api.open-loyalty.io/app_dev/api/doc

**Comment by pkarw** [comment]
As for now we do have only limited API documentation - you can find some information in here: https://github.com/DivanteLtd/open-loyalty/tree/master/backend

Would be great if you can contribute any docs - swagger/md/anything after playing with OL REST services.

You have API doc spreaded across source code right now :) So you can find out how to use specific module API in

```
/backend/src/OpenLoyalty/Bundle/*Bundle/Controller/Api/*Controller.php
```

for example in:
```
 class CampaignController extends FOSRestController
```

you have something like that:

```
    /**
     * Create new campaign.
     *
     * @Route(name="oloy.campaign.create", path="/campaign")
     * @Method("POST")
     * @Security("is_granted('CREATE_CAMPAIGN')")
     * @ApiDoc(
     *     name="Create new Campaign",
     *     section="Campaign",
     *     input={"class" = "OpenLoyalty\Bundle\CampaignBundle\Form\Type\CampaignFormType", "name" = "campaign"},
     *     statusCodes={
     *       200="Returned when successful",
     *       400="Returned when there are errors in form",
     *       404="Returned when campaign not found"
     *     }
     * )
     *
     * @param Request $request
     * @View(serializerGroups={"admin", "Default"})
     *
     * @return \FOS\RestBundle\View\View
     */
    public function createAction(Request $request)
```

**Comment by pkarw** [comment]
You Can  use this public address to take a look on our API doc:
http://backend.demo.openloyalty.io/doc
