### ISSUE TITLE
How do i deploy to google cloud?

### ISSUE THREAD

**Issue by vivekpadia70** [DivanteLtd/open-loyalty#26]
I am having some issues with deploying it with google cloud.
Can you help me with getting proper .yaml file for kubernetes?

Thank You.

**Comment by usidoretheblue** [comment]
Not exactly sure how you are looking to setup and install your instance, but your post piqued my interest in getting this installed in Google Cloud.

I am currently basing my install off of a Container-Optimized OS following this guide

https://cloud.google.com/community/tutorials/docker-compose-on-container-optimized-os

Going through the docker-compose install now will update with how things progress.

**Comment by usidoretheblue** [comment]
Buuuuuut to be expected I just ran into an issue with the npm install steps.

This particular VM instance is not designed to have additional software installed.

**Comment by vivekpadia70** [comment]
docker-compose only installs it locally.

So its good if you want it on your machine but to deploy it using kubernetes you need something else. You need to create some yaml files and run them simultaneously.

But there another way to do it using "kompose". Just need to run
```
kompose up
```

**Comment by usidoretheblue** [comment]
gotcha, yeah I am tracking now.

have you tried using kompose?

I just successfully installed on a Debian image I loaded up in GCP. Having it running on a f1.micro so it is nice and slow though lol.

**Comment by usidoretheblue** [comment]
lolz obviously you have not used the kompose because the docker-compose yaml file that we have is scripted for a local install.

I AM ALL THE WAY UNDERSTANDING NOW lolololol

**Comment by vivekpadia70** [comment]
So can you please give me docker-compose file for deployment?

**Comment by colejarczyk** [comment]
Hi,

We do not support Kubernetes yet. However, a lot of people asked about it and how to deploy Open Loyalty on Heroku, Amazon Cloud or Google Cloud we plan to add support for Kubernetes in near future.

**Comment by sultanmyrza** [comment]
we plan to add support for Kubernetes in near future.
2 years past.
Any updates?

**Comment by sultanmyrza** [comment]
we plan to add support for Kubernetes in near future, 2 years past.
Any updates?

**Comment by colejarczyk** [comment]
Hi @sultanmyrza 

Yes, we do support Kubernetes now. A few issues here were closed where others successfully deployed Open Loyalty on GCloud too.

Take a look at our documentation: https://docs.openloyalty.io/en/stable/developer/installation/kubernetes.html

Here is an example of Kubernetes manifests https://github.com/DivanteLtd/open-loyalty/tree/master/kubernetes

Here is an article about how we deployed and scaled Open Loyalty on AWS EKS https://www.openloyalty.io/building-a-massive-scale-loyalty-program-with-aws/
