### ISSUE TITLE
Google Deployment

### ISSUE THREAD

**Issue by fareedpatel** [DivanteLtd/open-loyalty#28]
We have been trying to deploy this application on google cloud using Kubernetes.
The instance used to deploy this application contains Debian v4.9 as its OS. And we installed Docker, GCloud, Kubernetes and Kompose as the tools for deployment. We built two docker images for the frontend and backend and linked them to the docker-compose file. Now in frontend image, we used (node:5) image from docker hub in Dockerfile of the frontend.

<img width="629" alt="screenshot 2017-08-15 11 50 45" src="https://user-images.githubusercontent.com/14962038/29313096-fd3ee08c-81af-11e7-9159-5cf3c96eb8de.png">

We also changed the docker-compose file as seen below:
<img width="669" alt="screenshot 2017-08-15 11 51 14" src="https://user-images.githubusercontent.com/14962038/29313141-4ca26310-81b0-11e7-8eb1-c9df10475fe6.png">

After changing the docker-compose file, we ran “kompose up” within the same directory.
which created the deployment and service ‘yaml’ file and then proceeded to run it.
We have pods as given below, but the frontend pod shows some error and some logs.
<img width="629" alt="screenshot 2017-08-15 11 57 46" src="https://user-images.githubusercontent.com/14962038/29313258-fb276cfa-81b0-11e7-8312-9793737780f9.png">
It says yarn not found. When we execute the same process on a local machine, it works as expected.

We are also trying to seek help from Google Support but your help and suggestions will also be highly appreciated.

**Comment by colejarczyk** [comment]
Hi,

We do not support Kubernetes yet. However, a lot of people asked about it and how to deploy Open Loyalty on Heroku, Amazon Cloud or Google Cloud we plan to add support for Kubernetes in near future.
