### ISSUE TITLE
openloyalty login issue

### ISSUE THREAD

**Issue by avinashsamala** [DivanteLtd/open-loyalty#29]
Hi Team,
               i installed open loyalty in my ubuntu system and i am trying to login admin in other system in my network with my system IP address but it not showing admin login page. please help me to fix this issue.

**Comment by colejarczyk** [comment]
Hi,

Are trying to access Open Loyalty from another computer? Have you installed OL using docker?

**Comment by avinashsamala** [comment]
Hi ,
      Thanks for replay. I have installed OL using docker in my ubuntu 16.04 LTS system. consider my system as a sever(http://192.168.1.33/8184/) and i am trying to access the application from another system it acts like a client and both are connected in same network. In this scenario how do we access the application at client side. we are unable to access the application from server ? and weather we need to install any 3rd party softwares at client side?. Please help me.

**Comment by colejarczyk** [comment]
Hi,

This problem is related to the network & server configuration, not improving or developing new features.

If you need assistance with Open Loyalty installation please contact us at support@openloyalty.io

**Comment by 7838099724** [comment]
Hello,
          I've Installed open loyalty and it's working fine in local environment but when I try to access it from another pc which is in same network but admin console is not being opened.
