### ISSUE TITLE
open-loyalty for magento

### ISSUE THREAD

**Issue by avinashsamala** [DivanteLtd/open-loyalty#31]
Hi 
    please give me any link/code of open loyalty program for magento 1.9

**Comment by colejarczyk** [comment]
Hi,

Check this out https://github.com/DivanteLtd/magento-open-loyalty

**Comment by avinashsamala** [comment]
Hi,
      Thanks for replay. we have already used the same github link but we are unable to find how to configure at magento admin side. Please check this screen shot https://prnt.sc/gb25nx and please help me to where we can get the API settings of open loyalty at admin side.

**Comment by colejarczyk** [comment]
Hi,

API URL is an address to Open Loyalty API, for example, http://backend.domain.com/ pointing at localhost:8181
Credentials are standard like "admin" as a username and "open" as a password if you haven't change them.
POS Identifier is a POS name added in the Open Loyalty: as a default, it could be "pos1".

For more support contact us at support@openloyalty.io
