### ISSUE TITLE
REST API port issue

### ISSUE THREAD

**Issue by avinashsamala** [DivanteLtd/open-loyalty#32]
Hi,
      i am installed open loyalty in my ubuntu system. I am able to access all links given in github link https://github.com/DivanteLtd/open-loyalty except REST API Port and it's showing error like in below screen shot link.
screen shot: http://prntscr.com/gb1aru

**Comment by colejarczyk** [comment]
Hi,

You trying to access a route that not exists. Please use http://localhost:8181/doc to see API documentation and all available URLs.

**Comment by avinashsamala** [comment]
Hi 
    Thanks for your replay
