### ISSUE TITLE
How to install In Windows?

### ISSUE THREAD

**Issue by NagarajuKasa** [DivanteLtd/open-loyalty#33]
We would like to know how to install open-loyalty in windows 10.
 please let us know the steps and procedure please help me it would be appreciated. thanks

**Comment by colejarczyk** [comment]
Hi,

Please use Vagrant to install OL. It's not possible or at least very hard to run OL in Windows 10.

**Comment by NagarajuKasa** [comment]
Thanks for your reply i will check and get back to you.
