### ISSUE TITLE
Database for Open-Loyalty

### ISSUE THREAD

**Issue by avinashsamala** [DivanteLtd/open-loyalty#35]
Hi
     In open loyalty we are creating rules, customers, earning point rules and segments and those are displaying in admin but where the data storing and their is any database for open loyalty and which location it exits.

**Comment by Shiva-android** [comment]
same thing i am too looking for database of open-loyalty, if any one know this, please tell us...

**Comment by colejarczyk** [comment]
Hi,

The database is stored in the "db" container using Postgresql. Read Model is stored in the "elk" container using Elastic Search.
