### ISSUE TITLE
How to Deploy to AWS Correctly?

### ISSUE THREAD

**Issue by gujiman** [DivanteLtd/open-loyalty#36]
Could you give us a tutorial on how to deploy to AWS correctly? What settings to use? Will the Free tier be enough for this app? Looks like this app is a nightmare for everyone to deploy.

**Comment by colejarczyk** [comment]
Hi,

@gujiman in case of assistance in the installation of the Open Loyalty, I suggest contacting our support and maintenance team via support@openloyalty.io. Our core product team covers only issues connected with improving the product or developing new features.
