### ISSUE TITLE
Openeloyalty running issue

### ISSUE THREAD

**Issue by avinashsamala** [DivanteLtd/open-loyalty#37]
Hi,
     is it required to execute "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up" command every time to start open loyalty in system.

**Comment by Shiva-android** [comment]
@avinashsamala  that command will build the packages freshly everytime, so try this one  ( docker-compose start ) ...

**Comment by colejarczyk** [comment]
Hi,

@avinashsamala this command is for development purpose and you need to run it every time. You can also add "-d" parameter to run docker as deamon. Please refer to the Docker documentation.
