### ISSUE TITLE
Installation Error - Debian 9

### ISSUE THREAD

**Issue by luisvarca** [DivanteLtd/open-loyalty#40]
Using fresh install on Debian 9 -- not using appliance.

Everything is fine until: phing setup, getting this failure:

```
OLOY > setup:

  [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  No handler found for uri [/oloy.customer_details] and method [POST]


oloy:user:projections:index:create [-drop-old|--drop-old] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>


BUILD FAILED
/root/open-loyalty/backend/build.xml:22:120: Task exited with code 255
Total time: 2.4753 seconds

```

Any suggestions?

**Comment by colejarczyk** [comment]
Here, our core product team covers only issues connected with improving the product or developing new features.

If you need assistance with Open Loyalty installation the write on the support@openloyalty.io
