### ISSUE TITLE
admin currency setting

### ISSUE THREAD

**Issue by lalitkt4** [DivanteLtd/open-loyalty#41]
Hi,
How can i add new currency from admin cockpit. Please help

Thanks

**Comment by colejarczyk** [comment]
Hi,

You can add a new currency only programmatically. See OpenLoyalty/Bundle/SettingsBundle/Form/Type/SettingsFormType.php at line 63

**Comment by catbuilts** [comment]
Nerver mind, I found this here:

https://github.com/DivanteLtd/open-loyalty/blob/882b80963f2f4e3605c7dfb4b75f9a20e6d42a51/frontend/src/component/global/data/DataService.js

Thank you
