### ISSUE TITLE
Postgresql Issue in installation

### ISSUE THREAD

**Issue by AbooKahn** [DivanteLtd/open-loyalty#42]
I am stuck due to a following issue in the installation:
open_loyalty_postgresql | ERROR: relation "ol__settings" does not exist at character 210
open_loyalty_postgresql | STATEMENT: SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.integer_value AS integer_value_3, t0.string_value AS string_value_4, t0.boolean_value AS boolean_value_5, t0.json_value AS json_value_6 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'integersettingentry', 'stringsettingentry', 'booleansettingentry', 'jsonsettingentry') LIMIT 1

Will be glad if you could assist us in installing the product.

**Comment by karolbzik** [comment]
@AbooKahn in case of assistance in the installation of the Open Loyalty, I suggest contacting our support and maintenance team via support@openloyalty.io. Our core product team covers only issues connected with improving the product or developing new features.
