### ISSUE TITLE
Frontend just spins

### ISSUE THREAD

**Issue by mbundgaard** [DivanteLtd/open-loyalty#47]
Hi guys

I'm all new to open-loyalty, and trying to take it for a spin.

I got the containers up and running and have deployed the demo data, but when accessing the three panels, I just get the red spinner that spins indefinitely.

I can fetch the API documentation and /api/translations returns valid data - so I assume the problem is with the frontend, but at this point, I'm not sure how to investigate further.

I've tested with both v1.1 and v1.2, same result.

If anyone has any pointers, it would be much appreciated.

Thanks in advance!

/Martin

**Comment by mbundgaard** [comment]
Ok, so frontend could not connect to backend API - I changed the url with gulp config/compile to use the IP of the host.

I don't know docker networking well enough to know if localhost should have been sufficient, but given that this was the default value, I guess so.

Again, if anyone has any input, it would be much appreciated.

/Martin

**Comment by PabloThiele** [comment]
Same here, what's the common approach to install that on a host to be tested remotely? The actual default config only runs fine on a localhost approach. Since several people should work together to provide a better test we need this working remotely. 

Thanks in advance

**Comment by colejarczyk** [comment]
Hi,

Edit parameters.json file in the frontend directory to point a proper API URL. 

A docker-compose expose ports of backend (api) container to the host machine so you don't need to know container internal ip address.

**Comment by PabloThiele** [comment]
That's make the deal! Before the docker-compose startup updated the parameters.json with my specific host and worked fine. Thanks :)

**Comment by cameronezell** [comment]
I'm still running into this same issue. I was running remotely at first so I updated the parameters to include the remote server address, but that didn't work. I tried locally in VirtualBox and I'm still getting the same problem.

**Comment by eligiable** [comment]
Hi There, 

I'm also having the same issue, changing IPs, pointing URL, accessing Locally, nothing worked.

Its just keep showing the Loader on the Screen.

Please share some steps to fix this.
