### ISSUE TITLE
locate db, pg_hba.conf in ubuntu?

### ISSUE THREAD

**Issue by sbkumar25** [DivanteLtd/open-loyalty#49]
Hi,
I would like to know about the followings...
1.Installed open-loyalty in Ubuntu 14.04, where i can locate the installed db & pg_hba.conf file?

2. How to take backup using pgdump?
below error msg thrown...
pg_dump: [archiver (db)] connection to database "postgres" failed: could not connect to server: Connection refused
 Is the server running on host "127.0.0.1" and accepting
 TCP/IP connections on port 5432?

Please help us to resolve the above said 2 points soon.
Thanks in advance.

**Comment by colejarczyk** [comment]
Hi,

Have you installed Open Loyalty using docker-compose? If so, you need to expose a "5432" port to your host machine. 

All configuration files are in the "db" container so the command "docker exec -it open_loyalty_postgresql bash" gives you a root access to the container. 

Be aware those changes will be available only on your local container. If you want to do anything more, extend "postgres:9" with you customer Dockerfile.

**Comment by sbkumar25** [comment]
Thanks colejarczyk
yes, installed. But we want to take db backup from the postgresql used in open loyalty. Please help.

**Comment by colejarczyk** [comment]
In the docker-compose.dev.yml add follow configuration:

```json
  db:
    ports:
      - "5432:5432"
```

Remember to run Open Loyalty using "docker-compose -f docker-compose.yml -f docker-compose.dev.yml up"

**Comment by sbkumar25** [comment]
Thanks, will check it and update.

Cant send invitation mail to Referrals?
Swiftmailer is not working. How to enable it? Please advise.

**Comment by sbkumar25** [comment]
hi,
Thanks the db backup works now.
docker exec -t 97fc6202d02d pg_dumpall -c -U postgres > dump_`date +%d-%m-%Y"_"%H_%M_%S`.sql
We have used the above command.
Thanks again.
---
Open Loyalty cant send invitation mail to Referrals?
Swiftmailer is not working. How to enable it? Please advise.
