### ISSUE TITLE
Cd ol

### ISSUE THREAD

**Issue by Nanotaha** [DivanteLtd/open-loyalty#50]
I am new to programming 
I downloaded Vagrant and Virtual Box aswell
I ran cmd to run the vagrant and executed 
'vagrant up'
'vagrant ssh '

So far so good
but got to 
'cd ol' and got this

The system cannot find the path specified.

C:\Users\ligia>docker-compose exec backend phing demo
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

Help please...

**Comment by phamnamlong** [comment]
Honestly, the installation using Docker and Vagrant are just pain in the a**. I have decent knowledge of programming skills and system in general but both methods take ages for me. Why not just include all of the source code here instead of require prior huge frameworks??

**Comment by Tjokian** [comment]
Hi @Nanotaha, you need to run vagrant command inside openloyalty folder. 
So after you execute vagrant run and vagrant ssh, folder ol will be there.
