### ISSUE TITLE
docker-compose exec backend phing demo showing error

### ISSUE THREAD

**Issue by Tjokian** [DivanteLtd/open-loyalty#51]
Hi Guys,
Im trying to install using vagrant in windows 10 pro.
When i execute docker-compose exec backend phing demo ,i got this error.

ubuntu@ubuntu-xenial:~/ol$ docker-compose exec backend phing demo
Buildfile: /var/www/ol/backend/build.xml

OLOY > generate-jwt-keys:

     [echo] JWT tokens already exist in app/var/jwt/!

OLOY > demo:

Warning: require(/var/www/ol/backend/app/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/ol/backend/app/autoload.php on line 13

Call Stack:
    0.0001     385824   1. {main}() /var/www/ol/backend/bin/console:0
    0.0002     387712   2. require('/var/www/ol/backend/app/autoload.php') /var/www/ol/backend/bin/console:17

Fatal error: require(): Failed opening required '/var/www/ol/backend/app/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/ol/backend/app/autoload.php on line 13

Call Stack:
    0.0001     385824   1. {main}() /var/www/ol/backend/bin/console:0
    0.0002     387712   2. require('/var/www/ol/backend/app/autoload.php') /var/www/ol/backend/bin/console:17

BUILD FAILED
/var/www/ol/backend/build.xml:48:43: Task exited with code 255

Total time: 0.1082 seconds

I already execute:
vagrant up
vagrant ssh
cd ol
docker-compose up -d

Did i miss anything? Thanks for your attention!

**Comment by colejarczyk** [comment]
Hi @Tjokian 
We do not support Windows platform. Please use docker or Vagrant.
