### ISSUE TITLE
errors in crontab file, can't install.

### ISSUE THREAD

**Issue by uvieugo** [DivanteLtd/open-loyalty#52]
After running `docker-compose up -d`, at STep 8/19 i get the following

```
Step 8/19 : RUN crontab /var/crontab.txt
 ---> Running in ac7ab42155b1
"/var/crontab.txt":1: bad minute
errors in crontab file, can't install.
ERROR: Service 'php' failed to build: The command '/bin/sh -c crontab /var/crontab.txt' returned a non-zero code: 1
```
Any ideas how i can resolve this. 

I am running on Vagrant/VirtualBox

Thanks

**Comment by colejarczyk** [comment]
Hi @uvieugo 

Please check newest changes in Vagrantfile.

**Comment by uvieugo** [comment]
Hi @colejarczyk 

I still had the same error, However i was able to fix it by editing the crontab.txt and removing the line in between the two entries.
