### ISSUE TITLE
install Open Loyalty at CentOS VirtualBOX guest over Windows 7 host 

### ISSUE THREAD

**Issue by aazzim** [DivanteLtd/open-loyalty#53]
I installed virtualbox and vagrant and docker , however I don't know from where can I run the rest of commands in the guide such as "docker-compose up". BTW I run CENTOS  
please help

**Comment by colejarczyk** [comment]
Hi @aazzim 

If you use Vagrant please log in on the machine using "vagrant ssh" and then you can execute all commands.

**Comment by MarcioDuran** [comment]
Good morning everyone !!!

I'm starting now with Open Loyalty, I'm having problems with docker-compose:
The error follows:
**docker-compose version 1.24.1, build 4667896b**
[vagrant @ localhost ~] $ **docker-compose up**
ERROR:
         Can't find a suitable configuration file in this directory or any
         parent Are you in the right directory?
                                                                             
         Supported filenames: docker-compose.yml, docker-compose.yaml
                                                                             
What is happening ?
