### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by websterac87** [DivanteLtd/open-loyalty#55]
Trying to install with docker, use command docker-compose up and eventually get this

`open_loyalty_db | ERROR:  relation "ol__settings" does not exist at character 210
open_loyalty_db | STATEMENT:  SELECT t0.id AS id_1, t0.setting_key AS setting_key_2, t0.dtype, t0.integer_value AS integer_value_3, t0.json_value AS json_value_4, t0.string_value AS string_value_5, t0.boolean_value AS boolean_value_6 FROM ol__settings t0 WHERE t0.setting_key = $1 AND t0.dtype IN ('settingsentry', 'integersettingentry', 'jsonsettingentry', 'stringsettingentry', 'booleansettingentry') LIMIT 1
open_loyalty_db | ERROR:  relation "ol__segment" does not exist at character 196
open_loyalty_db | STATEMENT:  SELECT o0_.segment_id AS segment_id_0, o0_.name AS name_1, o0_.description AS description_2, o0_.active AS active_3, o0_.customers_count AS customers_count_4, o0_.created_at AS created_at_5 FROM ol__segment o0_ WHERE o0_.active = $1`

**Comment by aazzim** [comment]
i got the same error , any help please

**Comment by websterac87** [comment]
Why isn't there a simple installation guide. its missing bits all over the place. the hours I have wasted on this.
