### ISSUE TITLE
 In developer mode i m facing  this isssue.

### ISSUE THREAD

**Issue by G-Deepak** [DivanteLtd/open-loyalty#56]
![screenshot from 2017-11-30 14-51-14](https://user-images.githubusercontent.com/22263670/33423144-fea9c162-d5dd-11e7-8ac5-7b747b532350.png)

commons.js:33548 GET http://openloyalty.localhost/app_dev.php/api/translations net::ERR_CONNECTION_REFUSED
(anonymous) @ commons.js:33548
sendReq @ commons.js:33281
serverRequest @ commons.js:33033
processQueue @ commons.js:37840
(anonymous) @ commons.js:37884
$digest @ commons.js:39022
$apply @ commons.js:39320
bootstrapApply @ commons.js:22741
invoke @ commons.js:25829
doBootstrap @ commons.js:22739
bootstrap @ commons.js:22759
angularInit @ commons.js:22644
(anonymous) @ commons.js:54673
fire @ commons.js:84355
fireWith @ commons.js:84485
ready @ commons.js:85335
completed @ commons.js:85351
commons.js:35489 TypeError: Cannot read property 'message' of null
    at admin.app.js:40209
    at commons.js:128671
    at arrayEvery (commons.js:129416)
    at Function.every (commons.js:137985)
    at errorCallback (commons.js:128670)
    at processQueue (commons.js:37840)
    at commons.js:37884
    at Scope.$digest (commons.js:39022)
    at Scope.$apply (commons.js:39320)
    at done (commons.js:33336) "Possibly unhandled rejection: {}"

**Comment by colejarczyk** [comment]
Hi @G-Deepak 

I think that php container failed to start. Cloud you provide the more detailed log from the console?
