### ISSUE TITLE
dev mode doesn't work

### ISSUE THREAD

**Issue by aazzim** [DivanteLtd/open-loyalty#58]
each time i run Open Loyalty in developer using the following line as per docs

docker-compose -f docker-compose.yml -f docker-compose.dev.yml up
i found the following errors 

open_loyalty_backend | /usr/local/bin/docker-php-entrypoint: 9: exec: ./init.sh: not found
open_loyalty_backend exited with code 127

when open website it keeps loading but doesn't open

**Comment by tjurczak** [comment]
Hi,

try to run docker-compose with rebuild images like this:

`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build`

**Comment by aazzim** [comment]
Hi

I would like to thank you. it works and login prompts poped up .

However , when i enter user:admin and password:admin , returns wrong
credential . should i request access from somewhere ? thanks in advance

br,
Ahmed

**Comment by tjurczak** [comment]
Hi,

you entered wrong password. You should use "open" as a password.

Login and password depend on section that you want to get to:
section | login | password
Admin | admin | open
POS | merchant@openloyalty.io | open
Customer | user@oloy.com | loyalty

**Comment by aazzim** [comment]
unfortunately, i tried admin and passowrd : open  but it returns " Bad credentials"
i tried other capital and small combinations but didn't work too
even the passowrds for rest of users such as merchant@openloyalty.io doesn't work too , gives me  "Bad credentials" too

**Comment by tjurczak** [comment]
I suppose that something was wrong durring installation process (data in database wasn't installed). Try to log in on php cointainer and call ```phing setup```. If it doesn't help then try to reinstall OL and watch logs.

**Comment by aazzim** [comment]
Thanks @tjurczak , problem solved and i can access development mode after running the  following:
$ docker run --name some-postgres -e POSTGRES_PASSWORD=mysecretpassword -d -p 5432:5432 postgres
Then 
$ docker-compose exec php phing setup
Then
$ cd docker/base
$ ./build_dev.sh

**Comment by tarek-aec** [comment]
Merchant Credental is:
Username: john2@doe2.com
Password: open

**Comment by sultanmyrza** [comment]
Credentials for all services as of Dec 2 (2019).
After successfull dev installation (docker version)

http://openloyalty.localhost:8182 - the administration panel 
(login: admin, password: open)
http://openloyalty.localhost:8183 - the customer panel 
 (login: user@oloy.com, password: loyalty)
http://openloyalty.localhost:8184 - the merchant panel
(login: john2@doe2.com, password: open)

Please give +1 or some indicator that it also worked for you
