### ISSUE TITLE
Only REST API not responding

### ISSUE THREAD

**Issue by venanx** [DivanteLtd/open-loyalty#59]
Hi,
I installed OpenLoyalty in my ubuntu system 16.04. 
I was able to access all links given in github link https://github.com/DivanteLtd/open-loyalty except REST API Port and it's showing error :

This site can’t be reached
admin.usemoti.com refused to connect.
ERR_CONNECTION_REFUSED

I have tested : 
http://localhost:8181/doc
http://localhost:8181

Looking for my system, I can't see 8181 as a listen port.
tcp6       0      0 :::8186                 :::*                    LISTEN     
tcp6       0      0 :::8182                 :::*                    LISTEN     
tcp6       0      0 :::8183                 :::*                    LISTEN     
tcp6       0      0 :::8184                 :::*                    LISTEN 

Could you help me solve this?

**Comment by tjurczak** [comment]
Hi,

check port 80, there will be API:

http://localhost/doc
http://localhost

It's mistake in documentation. We will fix it in latest version.

**Comment by catbuilts** [comment]
@venanx : I came into the same problem. Here is what I found in https://github.com/DivanteLtd/open-loyalty/blob/master/docker/prod/web/parameters.json file:

        "apiUrl": "http://openloyalty.localhost/api"

So, instead of http://localhost/doc, we should go to http://openloyalty.localhost/doc
The API now should be: http://openloyalty.localhost/api

**Comment by aazzim** [comment]
@tjurczak when i used port 80 as you recommended   
curl http://localhost:80/api/admin/login_check -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' --data-binary '{"_username":"admin","_password":"open"}'

i got the following error 

<html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.13.6</center>
</body>
</html>

what do you recommend as i cannot run an API commands

**Comment by aazzim** [comment]
i tried the following and it works with me 

curl 'http://openloyalty.localhost/api/admin/login_check' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept:application/json, text/plain, */*' --data-binary '{"_username":"admin","_password":"open"}'

**Comment by tjurczak** [comment]
@aazzim thanks for help,

I assume that problem has been fixed.
