### ISSUE TITLE
Open source or not ? Very confused

### ISSUE THREAD

**Issue by Ditiwi** [DivanteLtd/open-loyalty#60]
On the site of Open loyalty it is said : 

> Enterprise License is required for projects with more than 200 Customers

To have the open source version, you have to : 

> Ask for price

?!

**Comment by karolbzik** [comment]
Please check the license for Open Loyalty Community Edition here https://github.com/DivanteLtd/open-loyalty/blob/master/LICENSE.

If you have a small project with less than 200 customers registered in a loyalty application you can use Open Loyalty in the Community Edition, it's free. For projects with more than 200 customers - you need to purchase the license for Open Loyalty Enterprise Edition.

If you have any questions - please drop me a line at karl@openloyalty.io.

**Comment by Ditiwi** [comment]
Ok, is not open source, it's free under 200 custormers. The business arguments on your site are therefore wrong.
