### ISSUE TITLE
Cannot open the website when building without docker

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#61]
I can run the project with Docker, but when it comes to building the project without it, I'm really in trouble.
Please help me to build the project without docker or Vagrant.

Here is some more details:
I have installed  a local mail server, elasticSearch 2.2, php, Postgresql and nginx. 
In addition, I have run 2 commands at "_backend_" folder:

      composer install
      phing setup

These commands finished successfully. But I cannot open the pages, like _http://localhost:8182_. It returned: 

      This site can’t be reached
      localhost refused to connect.

 I'm wondering how I can open the pages after these two commands. I have tried: _phing demo_, or _composer up_ at "_Backend_" folder, but it didn't work. 

I would appreciate any help from you.
Thanks in advance.

**Comment by tjurczak** [comment]
Hi,

If you want to have the same working environment (without docker) you have to run all commands from dockerfiles manually on your environment (https://github.com/DivanteLtd/open-loyalty/tree/master/docker/prod).

I assumed that you made most of the things, but your error is not precise, so you need to check that:
- nginx process is running
- nginx listening on port 8182
- check if nginx virtual host is configured propertly

Without more details I am not able to help.

**Comment by catbuilts** [comment]
@tjurczak I didn't run the commands from dockerfiles. I will try to install the project again.
Thank you so much. Hoping it's gonna work this time.

**Comment by catbuilts** [comment]
@tjurczak I have been trying to build the project again but It's still errors. Please help me.

1. I'm wondering if it can run on **MacOS** ? I'm using my macbook and I dont know if it's a problem.

2. I followed your commands in the 2 dockerfiles, 
The first one (https://github.com/DivanteLtd/open-loyalty/blob/master/docker/prod/web/app-dockerfile) seemed to be ok, but the other, when I run _./init.sh_ at the last step, I got an error: 
    **runuser command not found.**  

    So, I change the line 23 (_runuser -s /bin/sh -c 'phing setup' www-data_) to _sudo -u www-data /bin/sh -c 'phing setup'_, and run again, but another error popped up: **Buildfile: build.xml does not exist!**.  My working directory is "/var/www/openloyalty". I dont know what I'm missing here. Why it couldnt find the build.xml file ?

Thanks

**Comment by tjurczak** [comment]
Hi @catbuilts,

Sorry, but we don't support MacOS. Moving commands from dockerfiles is possible if your native system is similar to debian/ubuntu otherwise there will be a lot of problems. We released OpenLoyalty using docker, becasue this is abstraction layer which lets developers running OpenLoyalty independently from operating system. Why are you going to run this project witout docker?

**Comment by catbuilts** [comment]
@tjurczak : ok, I got it. Thank you so much for supporting me.
