### ISSUE TITLE
failed docker command

### ISSUE THREAD

**Issue by dolphinsd** [DivanteLtd/open-loyalty#64]
I tried to follow your steps, command below fails

docker-compose exec open_loyalty_backend bash

error is 
ERROR: No such service: open_loyalty_backend

**Comment by catbuilts** [comment]
try _docker exec -it open_loyalty_backend bash_

**Comment by dolphinsd** [comment]
still an error
C:\Dev\TestLoyalty\Repo\open-loyalty\docker>docker exec -it open_loyalty_backend bash
Error response from daemon: Container f2c8b9398dabbadc288eab9e79255155b554563fdd055882855c11741060002f is not running

**Comment by catbuilts** [comment]
Run _docker ps_ to see the list of containers running.
Try to rebuild containers if you dont see them.

**Comment by dolphinsd** [comment]
install is missing ERROR: No such service: open_loyalty_backend, anyone has it?

**Comment by tjurczak** [comment]
Thanks @catbuilts for helping.
@dolphinsd Could you provide more information as catbuilts have mentioned if you still have this problem. Run:
```docker ps``` in order to see running containers.
