### ISSUE TITLE
php command issue

### ISSUE THREAD

**Issue by dolphinsd** [DivanteLtd/open-loyalty#66]
running "php phing.phar setup" produces php compile issue

 [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  Incorrect HTTP method for uri [/oloy.customer_details] and method [POST], a
  llowed: [GET, DELETE, HEAD, PUT]

  [Elasticsearch\Common\Exceptions\BadRequest400Exception]
  {"error":"Incorrect HTTP method for uri [/oloy.customer_details] and method
   [POST], allowed: [GET, DELETE, HEAD, PUT]","status":405}

oloy:user:projections:index:create [-drop-old|--drop-old] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by dolphinsd** [comment]
looks like an issue with latest elasticsearch
see https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_60_rest_changes.html

**Comment by catbuilts** [comment]
@dolphinsd  Use ElasticSearch ver 2.2, the problem should be solved.

**Comment by dolphinsd** [comment]
thanks, I just did that, you are right.
