### ISSUE TITLE
Documents for levels in Openloyalty

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#68]
I try to understand how **levels** work in Openloyalty. 

For more information, I built the project with Docker. It run smoothly. I can call almost api, except **api/transaction** which I made an issue [here](https://github.com/DivanteLtd/open-loyalty/issues/62) to seek help.

To create a new level, I use **api/level/create**. It has  a field called 
_condition value_. I don't really understand how this variable works.

As far as I guess, _condition value_ helps to define the level of customers. Each customer has a "Transactions value". At first, when customers sign up, they will be assigned to _level 0_ whose _condition level_ is 0. Latter on, when a customer makes some transactions which make his/her "Transactions value" passes the _condition value_ of the next level, _level 1_ for example, the customer can be upgraded **automatically** (or **not** ???) to the next level (i.e. _level 1_). Am I right ?

My questions are: 

1, How can I change  "Transactions value" of a specific customer ? First things first, what field we store the "Transactions value" which helps to classify customers' levels ? 
I guess I have to make some transactions with api/transaction to change it. However, I can't call this api. 

2, How can I set level for customers when creating new accounts for them ? For example, I want to create a new account, with level 1 at the beginning, is it possible?

3, Is the level of customers automatically updated when the "Transactions value" changes ?

So, I hope you can help me by answering these questions above. Please explain how levels work, and It would be great if you can give me more documents about the Openloyalty. It's really an interesting project, but It seems to lack documents. 

Thank you so much.

**Comment by colejarczyk** [comment]
Hi @catbuilts 

1. Yes, it's customer's CLV. So for every transaction a customer makes, Open Loyalty will calculate her/his CLV and check against existing levels. If CLV match with next level, a customer is assigned to the new level. OL picks always a level with the biggest reward. So if a current level has a reward 10 and next level only 9, then a customer stays with the current level. I've already answered your question about creating transaction in https://github.com/DivanteLtd/open-loyalty/issues/62

2. Yes, it's possible. Create a level 1 with condition value 0. Each newly registered customer will be assigned to this level automatically.

3. As I described in point 1, yes, it's automatically updated for each customer's transaction.

We're working hard on improving a documentation. You can check how we documented a first few modules here http://open-loyalty.readthedocs.io/en/latest/ We're continually improving documentation so please check it from time to time.

**Comment by catbuilts** [comment]
Hi @colejarczyk 
Thank you for your support. The answers for the first and the last questions are clear. I just have a bit concern on the second one.

In the second question, let's say we have **level 0** with _condition value_ is 0, and **level 1** with _condition value_ > 0 (e.g. **10** for example). Are there any ways to create a new customer with **level 1** ? 

Do we _must_ create a customer with **level 0** (as default), and then make a new transaction to edit his/her CLV, after that waiting for the program update the level ? Do we have any better solutions here ?

Thank you.
