### ISSUE TITLE
Schedule event in Openloyalty

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#69]
I actived the Earning Points Rule  **Login** (add some points for customers when they sign in their account). It worked smoothly. Now, I want another rule, let's say "add some points on customers' birthday", but I can't do it. There're no events called "birthday".

From the documents, I see that Openloyalty has **Customer Event Rule** in Earning Points Rule [From link here](https://github.com/DivanteLtd/open-loyalty/blob/master/backend/doc/examples/custom_events/index.rst).

As far as I know, we have to call api, for example  
     _api/v1/earnRule/follow_page/customer/00000000-0000-474c-b092-b0dd88..._
to add manually the point to customers' account.

**I wonder if Openloyalty can trigger schedule events,** for example: 
On customers' birthday, can it **automatically** adds some points to their account ?

Here what I tried:
I added a new segment, set its type to "Anniversary", then the next Type to "Birthday", and another parameter called "days". **What does "days" mean ?** I set it to 10, but I dont really understand.
After that, I created a new Earning Points Rule, tried to use the segment Birthday that I created before. Finally, I created some new customers, set their birthdays to today, but it seemed nothing happened.

So, how can trigger a schedule event in Openloyalty ?

Hoping you can help,
Thanks.

**Comment by colejarczyk** [comment]
Hi @catbuilts 

There is no built-in earning points rule for customer's birthday. As you already figure it out, you have to call API to add points to customer's account with custom earning points rule. Nevertheless, it's a nice feature that we possibly could add to Open Loyalty. What do you think @kbzik ?

As for segmentation, if you use "Anniversary" with type "Birthday", the field "days" mean "Show me customers that will have a birthday from today to today plus X days". So if you put 10 days then in this segment you will see customers that will have a birthday in next 10 days from now (including today).

You can create a new segment "Anniversary" with type "Birthday", set days to 1 and then create a product purchase earning points rule with a target set to this newly created segment. However, a customer will receive a birthday reward for every purchase in that day.

Please be aware that client can change her/his birthday every day.
