### ISSUE TITLE
Installation Alternative

### ISSUE THREAD

**Issue by chaozdjinn** [DivanteLtd/open-loyalty#7]
Is it possible to install the application without using Docker or Symphony? Old school way.

thanks

**Comment by BlackWebWolf** [comment]
Without Docker, as bare metal - yes. Without Symfony - no, it as a base, so cannot be done without it.

**Comment by chaozdjinn** [comment]
lets say I don't have access to the terminal...  is it still possible?

**Comment by BlackWebWolf** [comment]
No, it is not on server. Yet You can download it to Your workstation, get symfony and all packagist stuff, and upload it via ftp.

**Comment by chaozdjinn** [comment]
IC... will try try...
Can I request a ready made package for web installation? Lets say some people doesn't have access to the terminal... would be nice to have a web install feature.

thanks

**Comment by colejarczyk** [comment]
@chaozdjinn I think it is not possible. Open Loyalty is based on Symfony framework and it's a hard dependency. Also, I would argue is it possible to add the web install feature as Open Loyalty, but who knows.

IMHO, the minimal requirement for the server is a virtual server with access to the terminal.

**Comment by pkarw** [comment]
Hi guys, now the Vagrant alternative is available (please take a look at README). Do you think that webcast showing installation process on popular cloud providers like DigitalOcean or bare AWS would help? @chaozdjinn @BlackWebWolf ? We could post such short video next week

**Comment by chaozdjinn** [comment]
@colejarczyk i like to have an option to install it on a limited environment  ( ftp + php + mysql access only ) , i dont have the luxury of having a VPS or Docker :( I'd like to see something like ... a) unzip, b) enter config settings, mysql username and pass, c) check dependencies, d) run web installer, e) cleanup and use

**Comment by lalitkt4** [comment]
Hi,
   I am not able to install loyalty without docker. i m getting
/var/www/html/open-loyalty-master/backend/build.xml:26:102: Task exited with code 1 
this error.
is any documentation available or installation guide for without docker installtion

**Comment by colejarczyk** [comment]
Hi,

@chaozdjinn  It's not possible to install Open Loyalty as you described.

@lalitkt4 
The error is somehow related to the database because command failed on loading fixtures. Can you paste last 100 lines of log to see what happened? 

It is possible to install Open Loyalty without Docker, but it requires good skills to install and configure all required dependencies manually. I suggest installing OL using Docker or Vagrant.

**Comment by gujiman** [comment]
@pkarw do you have a short video on how to install OL on AWS. Cheers in advance!

**Comment by pkarw** [comment]
@gujiman unfortunately not yet :/
