### ISSUE TITLE
receive {"error":{"code":404,"message":"Not Found"}} with any POST or GET  APIs

### ISSUE THREAD

**Issue by aazzim** [DivanteLtd/open-loyalty#70]
i succeeded to run authorize API , but when i put the retrieved token in any other POST or GET API returns the following error {"error":{"code":404,"message":"Not Found"}} 

what i did i used all string in the token field

1. run authorize API :
# curl 'http://openloyalty.localhost/api/admin/login_check' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept:application/json, text/plain, */*' --data-binary '{"_username":"admin","_password":"open"}'

i used the token string reterived here:
{"token":"eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE1MTgyODUzNDAsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlkIjoiMjIyMDAwMDAtMDAwMC00NzRjLWIwOTItYjBkZDg4MGMwN2UyIiwibGFzdExvZ2luQXQiOiIyMDE4LTAyLTA5VDE1OjM0OjIyKzAxMDAiLCJpYXQiOiIxNTE4MTk4OTQwIn0.P7d4AOa7yhpt2AskXBwBD7_Va9Ny0z7c6u-qzgCRUKnfa8YaJPTvfQZB228jx94BfmiNo5SODHnfTVu4yMVMp03Ml7EzU6Kk2f0FEHDzluytr9i0lG7CqgttteVwlwUogn-5x3dvmnnJ0zG4nGV89KgGO669RCAlZMJPMRISCnrw6u7ZsLecwxQYJnH1NVhpWz_WCFlUtOb2fgo3EV3oPwXlg_rhWH4egnzsiIGsZGznlYssd6fCrPlqwDmv6MOHSTyuU25HDqD8TW_ZpsOYW2xd6enwhA6cZmMKPSx508UBbiN4-n6gzy9_xcrEJpBtscOyYqM4j5XGUAg9gHAU53XOB0XVzQ8oX5NZM5DPkztkp7Fpvzee40S4Aa5iut7NWMxSRfNt_zcXmMP2Uv-kF-7ahu2PxeXBbatWCDwWK9E9KCQjn0vRbtTCjEUI0ZwUjiE4IIp1ITYFE74KUX-U9JYIifTTwOP36q8MuZAihipa7hhek4FdLy3vonZwfDbx9R_6IMQJ51LU6S5_C-ESeLhsB658ZwQr9DhzZV3ZRmT9YVGYn4ImypyKCFddwNnP-n60PinWipfxLyJW34QSpQA8QACbaVGwomOr6E23n7Pmu0OOYB6Mugodz6V7FEyerfo7srHhtDaS3I3wcCFakiatjLoG-dpExlaVbvy35m0","refresh_token":"b63888c76998d12845c242756631d139862f8d7b0c3270ff157c21614041b685e719ec7b776a69c76db164fa4290f8383d8cdafa2b163c94ecf17a6d754634d7"}

2. when run any API such as 

curl 'http://openloyalty.localhost/api/admin/analytics/customers -X "GET" -H "Accept: application/json" -H "Contenttype: application/x-www-form-urlencoded" -H "Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXUyJ9.eyJleHAiOjE1MTgyODUzNzgsInVzZXJuYW1lIjoiYWRtaW4iLCJyb2xlcyI6WyJST0xFX0FETUlOIl0sImlkIjoiMjIyMDAwMDAtMDAwMC00NzRjLWIwOTItYjBkZDg4MGMwN2UyIiwibGFzdExvZ2luQXQiOiIyMDE4LTAyLTA5VDE4OjU1OjQxKzAxMDAiLCJpYXQiOiIxNTE4MTk4OTc4In0.j7S_OLSSxUXlSu2aWJrW-oMrZVjW5OhBM6x7kKHjxkMFX0mt1vhRVL1WjYm6qSrWxygekEUfct9xoJGT77w8IRiOCzQFCoi9jmjEO80G6WBE-TefQtkSJw1mB57hHuNtcZq5-xzv01b3DhyaGo4KDMQg0aZRk3muRDDORNVfn3-xupSrOGy2_N6BAED74siR1Mn9817nbZIeGL_aY0EK2CxS6PTxPfefbtjTJAZVKLIIWT713pl8ODhvtmqTeEr5ovwvOBGVK8KFJ7aD7URZzIDei7O0sMZAoCzaw6QEWczyX49uu8nDFp8itBr6R3U7Rau8iL-uyS-R7BZZGQnw_F-87oOqsR6jxWia6cAbmjbCrWrm7Oy3zab3Xshr3ygX19vJxyRaps_BfCIBU8VIg6Z2ZWwlfam1R6SvzbdjkTRDc_jNGHzItLjzi94RrExMILAaJwLZmyzC5_kcGfkb1rAZhSUBCqtR8fOaXmQAHiYvlXZqA6u6CiHbVXhR4knAh7mr0FLqDIHGLyX9zOnRm7VsC_mg5zo1naRwONrOOEJcboVRosnNLVQ85OZkENgWYtR_bwV1iE5unurB8QDbyISMQl5FNGh6b9rT1N4v120TgPjY5Cs9YjvbpsHDbtfQolAxNyTEtaGEP-fA4q0QthmlLYCcZLzKXJa2I4PsML8"'

Get the {"error":{"code":404,"message":"Not Found"}}

**Comment by colejarczyk** [comment]
Hi @aazzim 

Please look at our API documentation available http://open-loyalty.readthedocs.io/en/latest/api/index.html

It's still in progress but it may help you.
