### ISSUE TITLE
Issue in building

### ISSUE THREAD

**Issue by arfeen** [DivanteLtd/open-loyalty#71]
Im trying to build using:

`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build
`
But I cans see that backend and frontend are crashing and exiting with errors as shown below:

```
open_loyalty_backend | Composer could not find a composer.json file in /var/www/openloyalty
open_loyalty_backend | To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
open_loyalty_backend exited with code 1
open_loyalty_frontend | 2018/02/13 14:46:17 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/backend.conf:14
open_loyalty_frontend | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/backend.conf:14
open_loyalty_frontend exited with code 1
```
I'm still not able to install completely, I'm not sure why this product has no caretaker, we can even buy it but we need to see it how it works so we can build our app around it.

Thanks.
Arfeen

**Comment by tjurczak** [comment]
Hi @arfeen 

Base on your logs we are not able to help you. Could you provide more logs?

**Comment by tjurczak** [comment]
@arfeen it seems based on your another questions that you solved this problem.
