### ISSUE TITLE
How levels be updated in Openloyalty ?  

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#74]
I create three levels namely level0, level1, level2. Their Condition Values are 0, 20, 200, and their Reward Values are 1%, 2% and 3% respectively.

When a customer changes his/her CLV (by transactions), his/her level works smoothly, the level can up and down. For example, let's say we have a customer named John, his level is level1, and his CLV is 20. After he gets a transaction that has -2 grossValue, now his CLV is 18. It means his level now becomes level0. It worked in the way that I expected. 

But I'm confused when setting the level manually (by using api/customer/{customer-id}/level). For example, I have another customer named Jonh_2, his level is level0, with 0 CLV.  I change his level, from level0 to level1. So, if any change in John_2's CLV, does it impact on his level? As I tested, I'm aware that his level just can go up (upgraded to level2 if CLV >= 200), and it can NOT go down to level0 (No matter how low his CLV is)

I wonder that when we set level manually for a customer, ARE WE SETTING THE LOWEST LEVEL FOR THE CUSTOMER ? I see that no matter his/her CLV decreases, his/her level will not go lower the level which I set manually before.

Can you please tell me how exactly levels work in terms of updating. Thank you for your support.

**Comment by colejarczyk** [comment]
Hi @catbuilts 

Yes, you're correct. If you assign a customer to level manually, the customer cannot move lower than this level, only go higher. By lower I mean a customer can only go to the level with a higher reward.

If you update a level reward or condition values, you won't automatically recalculate all customers level. Open Loyalty will start using new level values only when a new transaction appears. 

Do you have any further questions? Is it clear now?

**Comment by catbuilts** [comment]
Hi @colejarczyk 

Thank your so much for your supporting. It's clear now.

**Comment by catbuilts** [comment]
Hi @colejarczyk 
I have one more thing to concern.

Let's say I have 100 customers, and I set level for some people manually. It means that these people become different than the other because their level can just go up. 

My question is that how can I get this list - the list of customers whose level just only goes higher. 
It is definitely easier for the Admin can control as well as handle these special people.

**Comment by tjurczak** [comment]
Hi @catbuilts,

It seems that i have answered for this questions in https://github.com/DivanteLtd/open-loyalty/issues/88.
