### ISSUE TITLE
An effective way to add points for a list of customers 

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#75]
I created a new Custom Event Rule. I know that whenever I want to add points for a customer with this Rule, I have to call an API (/api/v1/earnRule/{the-event-name}/customer/{the-customer-ID}). I got a problem. If I have a list of customers that I want to raise points, let's say a thousands of people. This means I must call the api thousands of times (each time to add points for only a customer in the list). It's obviously not effective at all. 

My question is that Are there any better solutions for this ? I expect we have an api to add points for a list of customers. In this way, I just need to call the api once, and it would be more effective. Is there any thing like this. 

I would appreciate any help.
Thanks in advance.

**Comment by arfeen** [comment]
I think what you are looking for is this:

http://backend.demo.openloyalty.io/doc#post--api-points-transfer-add

This API gets customer ids and add points. This take multiple customer ids in input.

**Comment by catbuilts** [comment]
@arfeen thanks for your idea. I'll check it out.
