### ISSUE TITLE
Symphony version upgrade caused phing setup errors

### ISSUE THREAD

**Issue by arfeen** [DivanteLtd/open-loyalty#77]
Until it was Symphony 3.2.13, it was well but upgrade of symphony caused some errors while running `phing setup` command. Please check the attached log file for details.

Almost of the services defined for phing are giving erros for deprecated functions/services and its not loading demo data in DB.

[phing.log.txt](https://github.com/DivanteLtd/open-loyalty/files/1786535/phing.log.txt)

**Comment by arfeen** [comment]
Any update on this ?

**Comment by tjurczak** [comment]
Hi @arfeen,

These are only warnings witout any negative affect on project. We will fix it in some next version.

**Comment by arfeen** [comment]
Because of this, I was unable to load sample data.
