### ISSUE TITLE
Small bug in admin page, when editing level for customers

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#78]
I go to the admin page to try to edit a customer's level.
a problem occurs when I have **more than 10 levels** (e.g. 11 levels):
When I click on **Select level** field, It drops down only the first ten levels, and misses the last one.

As I guess, When I load the page to edit customer's level, It calls **api/level** which just gets the first 10 levels as default. By changing **api/level** to **api/level?perPage=total_level**, this bug can be fixed.

**Comment by karolbzik** [comment]
@catbuilts thank you for reporting the bug, we will fix it in 2.4.0.

**Comment by colejarczyk** [comment]
@catbuilts I confirm that this bug has been fixed.

Tip: use perPage=-1 to get all records. It works globally for all API endpoints.
