### ISSUE TITLE
404 Not Found Issue

### ISSUE THREAD

**Issue by tommyat** [DivanteLtd/open-loyalty#8]
Hi,

I got a 404 page when uploading the source code to my server.

May I know what could be the causes?
---------
Oops! An Error Occurred

The server returned a "404 Not Found".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
---------

**Comment by colejarczyk** [comment]
Hi,

It seems that you're using the wrong URL/port as you're getting and error from the Symfony application. To confirm that, try to add "/app_dev/api/doc" at the end of the URL.

Please try with ports:
- 8182 - the administration panel,
- 8183 - the customer panel,
- 8184 - the merchant panel,

- 8181 - RESTful API port

You can see it here: https://github.com/DivanteLtd/open-loyalty/blob/master/docker-compose.yml

**Comment by tommyat** [comment]
Thank you colejarczyk.
It is the same result -'The server returned a "404 Not Found".' for /app_dev/api/doc
As I am not using docker, the ports respond with "refuse connection"
I think the error may be due to the absence of data in MySQL.
When I type "phing setup" on Windows, there is error "bin is not recognized as an internal or external command"

**Comment by colejarczyk** [comment]
If you're not using a docker, then can you write how you have installed application?

**Comment by tommyat** [comment]
Please find the steps I installed the application:
1. clone repository
2. composer install
3. setup parameters.yml

**Comment by just10minutes** [comment]
localhost:8181 is giving following error. is there any other setting required to access restful API?

I am running on Docker, other portals are fine
```
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused. 
```

**Comment by mkurzeja** [comment]
@just10minutes I think this is the correct and expected behavior as there is no action available under /.

Check if http://localhost:8181/doc is working (it should).

I will update the docs later and open a PR.

**Comment by jackymfp** [comment]
Hello, 

I want to follow up for my colleague named tommyat. 
The steps for his installation of Open Loyalty is as followed:
(1) clone repository
(2) composer install
(3) setup parameters.yml

However, error still occurs at installation of Open Loyalty. Anyone can advise how to fix the issue? Thanks!

**Comment by pkarw** [comment]
Hi guys, today I've just merged-in a Vagrant support added by @colejarczyk @jackymfp maybe this solve the issue:


You should have [Vagrant](https://www.vagrantup.com/downloads.html) and [Virtualbox](https://www.virtualbox.org/wiki/Downloads) installed prior to executing this recipe.

Then, please execute following commands:

```
vagrant up
vagrant ssh
cd ol
docker-compose up -d
docker-compose exec backend phing demo
```
