### ISSUE TITLE
Error "No releases available for package "pecl.php.net/apcu"- Openloyalty ver 2.2.0

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#81]
I have built the project **ver 2.0.1** successfully with docker.
Now I try to re-build it with the newest version **(2.2.0)**.

An error happened right after I run **docker-compose up**, at line **RUN pecl install apcu**:

```
Step 4/24 : RUN pecl install apcu

No releases available for package "pecl.php.net/apcu"
install failed
**ERROR**: Service 'php' failed to build: The command '/bin/sh -c 
pecl install apcu' returned a non-zero code: 1
```

I'm using Red Hat 7.4,
Docker version 17.06.1-ce, build 874a737,
docker-compose version 1.18.0, build 8dd22a9.

Do you have any ideas for the problem ?
Thank you for your help.

**Comment by tobiit** [comment]
Ran into the same problem. Cause: my box is behind a firewall and requires a proxy to connect to the internet. 
Following did the trick:
added the following line to open-loyalty/docker/prod/php/fpm-dockerfile : 
after 
`ENV SYMFONY_ENV="prod"  `

`RUN pear config-set http_proxy your.proxy:port`

obviously you need to repace your.proxy:port with your proxy information. if you require username/Passwort you need to add this to this line user:passwort@your.proxy:port

**Comment by catbuilts** [comment]
Hi @tobiit 

Your're right.
Thank you so much.
