### ISSUE TITLE
Problem with frontend when build in Server

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#82]
I'm trying to build Openloyalty version 2.2.0 in my server.

It's ok until I open the Admin page. The page just spin over and over. 
Perhaps, It's because **openloyalty.localhost/api** does not response.

I guess I have to change **openloyalty.localhost** to my server ip. 
I found the 2 paramaters files:
+ The first file from **Frontend** folder: https://github.com/DivanteLtd/open-loyalty/blob/master/frontend/parameters.json
In the file, the first line is: 
`"apiUrl": "http://localhost:8181/app_dev.php/api",`

I could not find **openloyalty.localhost** here, so I didn't make any changes to this file.

+ The second one from **docker/prod/web/** folder: https://github.com/DivanteLtd/open-loyalty/blob/master/docker/prod/web/parameters.json
The first line is
`"apiUrl": "http://openloyalty.localhost/api",`

I changed it to 
              `"apiUrl": "http://10.x.y.z/api",` (_10.x.y.z_ is my server ip).
Then, I stopped docker and run `docker-compose up` again, but it still didnt work.

Can you please help me to fix this.
Thank you in advance.

**Comment by arfeen** [comment]
I think it won't work like this, since after any changes, you need to rebuild the docker.

**Comment by bizr** [comment]
On the file
`frontend/src/config.js`
Change your settings to your own domains, then build the project again.
Also keep in mind you can use hosts file or static dns on your router to achieve the same result.
Hope this helps.

**Comment by tobiit** [comment]
I have the same problem. The suggestion mentioned above (frontend/src/config.js) and full rebuild does not work. Any more ideas? I am setting up on a sandbox in our corporate network located at openloyalty.corp.internal
calling `http://openloyalty.corp.internal:8182/#!/` results in a loading circle spinning. Calls are made to 
`http://openloyalty.corp.internal:8181/api/settings/logo` and other uri's on port 8181
but port 8181 is not exposed by any of the docker containers. Respectively any call to the api is not answered.
lsof -i:

> docker-pr  8170    root    4u  IPv6 130293      0t0  TCP *:8186 (LISTEN)
> docker-pr 27444    root    4u  IPv6 321973      0t0  TCP *:8184 (LISTEN)
> docker-pr 27456    root    4u  IPv6 322007      0t0  TCP *:8183 (LISTEN)
> docker-pr 27468    root    4u  IPv6 322032      0t0  TCP *:8182 (LISTEN)
> docker-pr 27479    root    4u  IPv6 322059      0t0  TCP *:http (LISTEN)

docker ps

> CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
> d2d637240533        docker_nginx        "nginx -g 'daemon of…"   20 minutes ago      Up 20 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:8182->3001/tcp, 0.0.0.0:8183->3002/tcp, 0.0.0.0:8184->3003/tcp   open_loyalty_frontend
> d5834793d486        docker_php          "docker-php-entrypoi…"   20 minutes ago      Up 20 minutes       9000/tcp                                                                                     open_loyalty_backend
> 8cba466160ce        mailhog/mailhog     "MailHog"                3 hours ago         Up 3 hours          1025/tcp, 0.0.0.0:8186->8025/tcp                                                             open_loyalty_mail
> e4260bd9f910        elasticsearch:2.2   "/docker-entrypoint.…"   3 hours ago         Up 3 hours          9200/tcp, 9300/tcp                                                                           open_loyalty_elk
> 3de677cc24c9        postgres:9          "docker-entrypoint.s…"   3 hours ago         Up 3 hours          5432/tcp   

                                                                                  open_loyalty_db

**Comment by catbuilts** [comment]
@arfeen Thank you, I will rebuild it.
@bizr Thank you for your suggestion about changing the file `config.js`. After that, I run **docker-compose build --no-cache** and it worked.
Now I can access the Admin page in server via my macbook.
One more a problem remains: http://10.145.198.61/api/settings/logo still doesn't response, so I cant see the logo. It shows this error [1].

@tobiit I think It calls **http://10.145.198.61/api/settings/logo** (It goes on port **80**, not **8181**), but It is still an error (please see [1] below). 
______
[1] Response when I access **http://10.145.198.61/api/settings/logo**

`Fatal error: Uncaught Gaufrette\Exception\FileNotFound: The file "logo/logo.svg" was not found. in /var/www/openloyalty/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php:336 Stack trace: #0 /var/www/openloyalty/vendor/knplabs/gaufrette/src/Gaufrette/Filesystem.php(99): Gaufrette\Filesystem->assertHasFile('logo/logo.svg') #1 /var/www/openloyalty/vendor/divante-ltd/open-loyalty-framework/src/OpenLoyalty/Bundle/SettingsBundle/Service/LogoUploader.php(43): Gaufrette\Filesystem->get('logo/logo.svg') #2 /var/www/openloyalty/vendor/divante-ltd/open-loyalty-framework/src/OpenLoyalty/Bundle/SettingsBundle/Controller/Api/SettingsController.php(135): OpenLoyalty\Bundle\SettingsBundle\Service\LogoUploader->get(Object(OpenLoyalty\Bundle\SettingsBundle\Model\Logo)) #3 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(151): OpenLoyalty\Bundle\SettingsBundle\Controller\Api\SettingsController->getLogoAction() #4 /var/www/openloyalty/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpK in /var/www/openloyalty/vendor/twig/twig/lib/Twig/Cache/Filesystem.php on line 55`

**Comment by arfeen** [comment]
@catbuilts I was able to build after modifying the host information wherever there was "openloyalty.localhost", I searched in files and changed with my desired one and it was all working after building. I used 
`docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build`
and it worked.

**Comment by colejarczyk** [comment]
To clarify things up. If you want to build Open Loyalty on the server under a certain domain you need to:
1. Change "apiUrl" in the ```frontend/src/config.js``` so the frontend application knows where an API is. For example http://api.example.com/api (without a slash at the end). 

If it's "dev" environment, no rebuild is needed, just refresh. If it's a production, which is loaded from then rebuild is required.

2. Change parameters in ```backend/app/config/parameters.yml``` (this file is autogenerated after Open Loyalty is installed):
- env(frontend_password_reset_url): 'http://admin.example.com/#!/password/reset'
- env(frontend_customer_panel_url): 'http://client.example.com/'

Now API knows where an admin and client panel are. In this step, you're required to clear the cache using ```bin/console cache:clear --env=prod``` (or dev if you're using development environment).

If you have any further questions you can ask me on this issue.
