### ISSUE TITLE
Available translations not returned in the Language selection

### ISSUE THREAD

**Issue by dymitar** [DivanteLtd/open-loyalty#83]
I'm trying to create new translation and to use it in the Settings / Language combo.
The translation is created successfully, shown in the translations screen and it is existing in the filesystem, but I don't see it (cannot select it) from the Language combo in the Settings. The only available selection is the current one (english.json).
If I set the new translation directly in the database it is used properly, and I see it in the Settings. But in this case the english is not available.

**Comment by catbuilts** [comment]
the same

**Comment by tjurczak** [comment]
Hi @dymitar,

It seems to bug in some newest versions of OL. We will fix it next version.

**Comment by colejarczyk** [comment]
Hi @dymitar 

Please check our latest version 2.6.0. This issue has been fixed.
