### ISSUE TITLE
Change Currency

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#84]
There are 3 default value for currency.
Now I want to add one more (actually, I just need to edit 1 out of the three).

I have found this #41, but I could not find the file that @colejarczyk said.
I have tried to look for it in docker containers, it's still not there.
Please help me by showing the location of the file.
Thank you.

**Comment by karolbzik** [comment]
@colejarczyk could you point that location?

**Comment by catbuilts** [comment]
I have found the file @colejarczyk said in **open_loyalty_backend** container:
_/var/www/openloyalty/vendor/divante-ltd/open-loyalty-framework/src/OpenLoyalty/Bundle/SettingsBundle/Form/Type/SettingsFormType.php_

I added one more currency.
But nothing happened when I reload the admin page.

What am I missing here?
Do I have to edit more in another file ?

Thank you.
