### ISSUE TITLE
Yarn install wait forever at "[2/4] Fetching packages..." step

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#85]
When I run `docker-compose up`, it just keeps getting stuck at **[2/4] Fetching packages...** step (please see the log [1] at the end of this post)

For more information:
Because my server is behind a proxy, so I have changed the dockerfiles a little bit. 
Basically, in **app-dockerfile**, I set **ENV http_proxy _my_proxy_**, **ENV https_proxy _my_proxy_** , and I added these 2 lines before `yarn install` command

```
# here my_proxy is 10.x.y.z at port 80
RUN yarn config set proxy http://10.x.y.z:80 
RUN yarn config set https-proxy http://10.x.y.z:80
```
_The full version of **app-dockerfile**, please see [2] at the end of this post._

Sometimes I can build the project successfully.  Normally, when it gets stuck at **[2/4] Fetching packages...** step, I just need to cancel and rebuild it (on the second time, it usually works out).
Today, I have built the project many times but it did work at all.
It got stuck at **[2/4] Fetching packages...** step like I said before.

I have did some research, and it seems some people have the same issue with yarn:
https://github.com/yarnpkg/yarn/issues/4412

Do you have any ideas about it ?
I really appreciate any help.
Thank you.

*Update:
I tried to build the project on my local computer, It still didnt work with the same issue.
_______
[1] Here is the log when I run **docker-compose up** (at the command: **yarn install --verbose**)
> 1/4] Resolving packages...
> verbose 1.111 Performing "HEAD" request to "https://github.com/squizlabs/HTML_CodeSniffer.git".
> verbose 2.449 Request "https://github.com/squizlabs/HTML_CodeSniffer.git" finished with status code 301.
> [2/4] Fetching packages...
> verbose 2.53 Performing "GET" request to "https://registry.yarnpkg.com/ace-angular/-/ace-angular-0.1.1.tgz".
> ...
> verbose 63.118 Performing "GET" request to "https://registry.yarnpkg.com/lodash._basecreate/-/lodash._basecreate-2.4.1.tgz".
> verbose 63.122 Performing "GET" request to "https://codeload.github.com/squizlabs/HTML_CodeSniffer/tar.gz/d209ce54876657858a8a01528ad812cd234f37f0".
> verbose 907.326 Error: https://registry.yarnpkg.com/jsoneditor/-/jsoneditor-5.9.6.tgz: unexpected end of file
>     at Zlib._handle.onerror (zlib.js:370:17)
> error An unexpected error occurred: "https://registry.yarnpkg.com/jsoneditor/-/jsoneditor-5.9.6.tgz: unexpected end of file".
> info If you think this is a bug, please open a bug report with the information provided in "/var/www/frontend/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> ERROR: Service 'nginx' failed to build: The command '/bin/sh -c yarn install --verbose' returned a non-zero code: 1

[2] My **app-dockerfile** file:
> FROM divante/open-loyalty-base-nodejs AS front
> 
> ENV http_proxy=http://10.x.y.z:80
> ENV https_proxy=http://10.x.y.z:80
> 
> COPY ./frontend /var/www/frontend
> WORKDIR /var/www/frontend
> 
> 
> #RUN npm cache clear
> RUN npm rebuild node-sass
> 
> #RUN yarn cache clean
> RUN yarn config set proxy http://10.x.y.z:80
> RUN yarn config set https-proxy http://10.x.y.z:80
> RUN yarn install --verbose
> 
> RUN npm run-script build
> 
> FROM divante/open-loyalty-base-nginx as www
> 
> RUN usermod -u 1000 www-data
> COPY ./docker/prod/web/bin/init.sh init.sh
> RUN chmod a+x init.sh
> RUN rm -f /etc/nginx/conf.d/*
> COPY ./docker/prod/web/backend.conf /etc/nginx/conf.d/backend.conf
> COPY ./backend/web/ /var/www/openloyalty/web
> COPY ./docker/prod/web/frontend.conf /etc/nginx/conf.d/front.conf
> COPY --from=front /var/www/frontend/dist /var/www/openloyalty/front
> COPY --from=front /var/www/frontend/rancher/entrypoint.sh /entrypoint.sh
> 
> ENV http_proxy=""
> ENV https_proxy=""
> 
> RUN chmod +x /entrypoint.sh

**Comment by catbuilts** [comment]
It seems like the problem lies on my Internet connection.
I close the topic now.
Sorry if It bothers you.

Thank you.

**Comment by andrewhenriquef** [comment]
@catbuilts I have seemed the same problem, how did you fix that?

**Comment by catbuilts** [comment]
Hi @andrewhenriquef 

It was on Internet Connection. My computer coundnt reach https://registry.yarnpkg.com/jsoneditor/-/jsoneditor-5.9.6.tgz because of the internet problem. 
Sometimes It got stuck because of "phantomjs" file (still couldlnt reach the internet).

I decided to use an npm repository server in my company, and it worked as I expected.
More details:
I changed the _app-dockerfile_ file to use the npm server:

> RUN npm set registry http://10.145.x.y:8080


manually download the "phantomjs" file and add it to docker container:

> COPY ./docker/phantomjs-2.1.1-linux-x86_64.tar.bz2 /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2


Hope it can help.

**Comment by andrewhenriquef** [comment]
Ty @catbuilts, I fixed it by doing it

Removing node modules from my project
> rm -rf /node_modules

Cleaning  yarn cache and installing it again
> yarn cache clean && yarn install

Everything works fine now

**Comment by bizr** [comment]
Try disabling IPv6, that was my issue!

**Comment by lemartins07** [comment]
> Try disabling IPv6, that was my issue!

How can i do this?

**Comment by balajibrk** [comment]
https://www.my-private-network.co.uk/kbhome/how-to-disable-ipv6-on-windows-10/
To disable IPv6

**Comment by christo8989** [comment]
Check your vpn connection.
