### ISSUE TITLE
elasticsearch - elk docker container not responding ...

### ISSUE THREAD

**Issue by tobiit** [DivanteLtd/open-loyalty#86]
When I execute the above mentioned command
`docker-compose -f docker/docker-compose.yml exec php phing demo `
I receive the following error (followed by gibberish HTML output)

> OLOY > demo:
>
> 22:43:09 ERROR     [console] Error thrown while running command "oloy:user:projections:index:create --drop-old -n". Message: "
...
> <h1>Network Error (dns_unresolved_hostname)</h1>
>  Your requested host "elk" could not be resolved by DNS.

`docker ps`
gives me

> <table>
> <tr>
> <th>CONTAINER ID</th><th>        IMAGE </th><th>              COMMAND   </th><th>               CREATED  </th><th>           STATUS     </th><th>         PORTS                     </th><th>                                                                     NAMES</th>
> </tr><tr><td>641d7dc12fbd</td><td>        docker_nginx    </td><td>    "nginx -g 'daemon ..." </td><td>  37 hours ago    </td><td>    Up 21 hours     </td><td>    0.0.0.0:8181->80/tcp, 0.0.0.0:8182->3001/tcp, 0.0.0.0:8183->3002/tcp, 0.0.0.0:8184->3003/tcp   </td><td>open_loyalty_frontend</td>
> </tr><tr><td>246c983525bc    </td><td>    docker_php      </td><td>    "docker-php-entryp..."  </td><td> 37 hours ago     </td><td>   Up 21 hours     </td><td>    9000/tcp   </td><td>                                                                                    open_loyalty_backend</td>
> </tr><tr><td>6739700a3cf2    </td><td>    postgres:9      </td><td>    "docker-entrypoint..."  </td><td> 38 hours ago    </td><td>   Up 21 hours     </td><td>    5432/tcp                 </td><td>                                                                      open_loyalty_db</td>
> </tr><tr><td>e863920a3bed    </td><td>    mailhog/mailhog    </td><td> "MailHog"        </td><td>        38 hours ago     </td><td>   Up 21 hours    </td><td>     1025/tcp, 0.0.0.0:8186->8025/tcp     </td><td>                                                          open_loyalty_mail</td>
> </tr><tr><td>01142eafab40   </td><td>     elasticsearch:2.2  </td><td> "/docker-entrypoin..."  </td><td> 38 hours ago   </td><td>     Up 21 hours     </td><td>    9200/tcp, 9300/tcp         </td><td>                                                                    open_loyalty_elk</td>
> </tr>
> </table>

I am running inside a vagrant machine.

Any idea what is happening here?

**Comment by tobiit** [comment]
I am trying to get a status from elasitcsearch by doing a:
`
curl -XGET 'http://elk:9200/_count?pretty' -d '
{
    "query": {
        "match_all": {}
    }
}
'
`

I get the following message:

> Network Error (tcp_error)
> A communication error occurred: "Operation timed out"
>   <table style="font-size:90%;font-family:'Courier New';color:#C00000">
>   <tr><td>Requested URL:</td><td>GET http://elk:9200/_count?pretty </td></tr>
>   <tr><td>URL Category:</td><td>none </td></tr>
>   <tr><td>Server IP address:</td><td>172.18.0.4 </td></tr>
>   <tr><td>Client IP address:</td><td>10.96.95.213 </td></tr>
>   <tr><td>User name:</td><td>  (if available) </td></tr>
>   <tr><td>Proxy:</td><td>EU-PAR-BC103 (10.72.184.72:9998) </td></tr>
>   <tr><td>Reason:</td><td>"Request could not be handled" </td></tr>
>   </table><br> <br>
>   </font>
>   <hr color='#C00000'><font color='#C00000'>
>   <small>generated 2018-03-28 09:34:09 (UTC)</small></font>
> 

`lsof -i`
gives me

> docker-pr  2326    root    4u  IPv6  22317      0t0  TCP *:8186 (LISTEN)
> docker-pr  2676    root    4u  IPv6  24902      0t0  TCP *:8184 (LISTEN)
> docker-pr  2688    root    4u  IPv6  26627      0t0  TCP *:8183 (LISTEN)
> docker-pr  2703    root    4u  IPv6  26644      0t0  TCP *:8182 (LISTEN)
> docker-pr  2714    root    4u  IPv6  24094      0t0  TCP *:8181 (LISTEN)

when logging into the docker container 
`docker exec -ti 01142eafab40 /bin/bash`
and executing 
`ps aux`
I get

> USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
> elastic+     1  0.8  5.7 4644564 233924 ?      Ssl  Mar27  10:13 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Xms256m -Xmx1g -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupan

any idea why elasticsearch is not responding?

**Comment by tobiit** [comment]
I flushed the cache, adjusted IP Adresses and created an entry in all /etc/hosts files for elk.

The process is now proceeding on my 8core XEON, 16GB Mem, 4 TB SSD Storage box as follows:

`docker-compose -f docker/docker-compose.yml exec php phing demo`

And this is the output - maybe any idea where I can increase the timeout:

> Buildfile: /var/www/openloyalty/build.xml
> 
> OLOY > generate-jwt-keys:
>
>    [echo] JWT tokens already exist in app/var/jwt/!
>
> OLOY > demo:
>
> 13:02:14 ERROR     [console] Error thrown while running command "oloy:user:projections:index:create --drop-old -n". Message: 
                        <TABLE border=0 cellPadding=1 >
                        <TR><TD>
                        
                        <h1>Network Error (tcp_error)</h1>
                        </TD></TR>
                        <TR><TD>
                        <FONT size=2 face="Helvetica">
                        A communication error occurred: "Operation timed out"
                        </FONT>
                        </TD></TR>
                        <TR><TD>
                        <FONT face="Helvetica">
                        The Web Server may be down, too busy, or experiencing other problems preventing it from responding to requests. You may wish to try again at a later time.
                        </FONT>
                        </TD></TR>
                        <TR><TD>
                        <FONT face="Helvetica" SIZE=2>
                        <BR>
                          <hr color='#C00000'>
  <font size="3" face="verdana" color='#C00000'>
  <strong>!! For assistance, please contact your local Service Desk! !!</strong>
  </font><br>
  <font size="2" face="verdana" color='#C00000'>
  To help us assist you more efficiently, please provide every available piece of information<br>
  by copying this entire text or making a screenshot if asked by Service Desk personnel. Many thanks!<p>
  <table style="font-size:90%;font-family:'Courier New';color:#C00000">
  <tr><td>Requested URL:</td><td>DELETE http://174.18.0.4:9200/oloy.customer_details?timeout=5s </td></tr>
  <tr><td>URL Category:</td><td>none </td></tr>
  <tr><td>Server IP address:</td><td>174.18.0.4 </td></tr>
  <tr><td>Client IP address:</td><td>10.96.95.214 </td></tr>
  <tr><td>User name:</td><td>  (if available) </td></tr>
  <tr><td>Proxy:</td><td>EU-PAR-BC103 (10.72.184.72:9998) </td></tr>
  <tr><td>Reason:</td><td>"Request could not be handled" </td></tr>
  </table><br> <br>
  </font>
  <hr color='#C00000'><font color='#C00000'>
  <small>generated 2018-03-30 11:02:16 (UTC)</small></font>
  </FONT>
</TD></TR>
</TABLE>

**Comment by tjurczak** [comment]
Hi @tobiit,

1. Do you use docker-compose files included in project?
2. Try to make:
```docker inspect docker_id```

and see what value is in section network/Aliases. You can use these aliases to connect with this container.
```
            "Networks": {
                "docker_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "elk",
                        "1c833732af5b"
                    ],
                    "NetworkID": "b8180bdb032f460618535574e69b6eea27b487443404b304854f74714e1d41f3",
                    "EndpointID": "a5ebced1a9d81b0447e1890b27bbc7c2fc2e2139d8d6a96347cbfc5e4bdd1181",
                    "Gateway": "172.22.0.1",
                    "IPAddress": "172.22.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:16:00:02",
                    "DriverOpts": null
                }
            }
```

**Comment by tobiit** [comment]
It is the last two day's of our Openloyalty Evaluation for Migration of our current Loyalty platform running for 1.2 Mio customers and unfortunately we have not been able to get it up and running. I got today and tomorrow left.

`docker ps`
> 01142eafab40        elasticsearch:2.2   "/docker-entrypoin..."   9 days ago          Up 6 minutes        9200/tcp, 9300/tcp                                                                             open_loyalty_elk

`docker inspect 01142eafab40`

>            "Networks": {
>               "docker_default": {
>                    "IPAMConfig": null,
>                    "Links": null,
>                    "Aliases": [
>                        "elk",
>                        "01142eafab40"
>                    ],
>                    "NetworkID": >"1e1d616921e79a058e6b0b40397cc1d666d106916276a9980b93be4d742acbbe",
>                    "EndpointID": >"c02ca7c41af91d090a4c3591dd565bd18221ce19233fbc7a23f6b8260b90c5e1",
>                    "Gateway": "172.18.0.1",
>                    "IPAddress": "172.18.0.3",
>                    "IPPrefixLen": 16,
>                    "IPv6Gateway": "",
>                    "GlobalIPv6Address": "",
>                    "GlobalIPv6PrefixLen": 0,
>                    "MacAddress": "02:42:ac:12:00:03",
>                    "DriverOpts": null
>                }
>            }

Thanks for your help.

**Comment by tjurczak** [comment]
I think that this problem is not related directly to open-loyalty but rather to docker engine. Could you provide more information what environment do you use (linux, windows) what docker version (docker toolbox for windows, or native version). Please check follow things:
1) Run OL ```docker-compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up```
2) ```docker exec -it open_loyalty_backend bash -c "ping elk"```
3) ```docker exec -it open_loyalty_backend bash -c "ping nginx"```
4) ```docker exec -it open_loyalty_backend bash -c "curl -XGET 'http://elk:9200/_count?pretty' -d ' { "query": { "match_all": {} } } '"```

**Comment by tobiit** [comment]
Running in VAGRANT on a LINUX BOX (ubuntu server).

Vagrant tells me that  "debian/contrib-stretch64" is pulled and installed.
The first build steps complete with no problems.

All docker containers respond to ping.

I can login to the php docker instance
`docker exec -ti 246c983525bc /bin/bash`
After logging into the php instance and executing e. g. the following command, it fails with above mentioned errors
`./bin/console oloy:user:projections:index:create --drop-old -n`

`docker exec -it open_loyalty_backend bash -c "ping nginx"`
> PING nginx (172.18.0.6): 56 data bytes
> 64 bytes from 172.18.0.6: icmp_seq=0 ttl=64 time=1.104 ms


`docker exec -it open_loyalty_backend bash -c "ping elk"`
> PING elk (172.18.0.3): 56 data bytes
> 64 bytes from 172.18.0.3: icmp_seq=0 ttl=64 time=1.700 ms

`docker exec -it open_loyalty_backend bash -c "curl -XGET 'http://elk:9200/_count?pretty' -d ' { "query": { "match_all": {} } } '"`
```
<HTML>
<HEAD><TITLE>Redirection</TITLE></HEAD>
<BODY><H1>Redirect</H1></BODY>
</HTML>
```

**Comment by tjurczak** [comment]
Hi @tobiit,

Your problem is strange. I noticed that you are using still the same containers (```9 days ago Up 9 hours ```), maybe good idea would be reinstall project from the beginning.

Bellow line showed us that elasticsarch container is accesible from backend container. This is OK.
```docker exec -it open_loyalty_backend bash -c "ping elk"```

This line showed us that elastic search has some problem with responding. ES is alive but return some redirection (this is the main problem in my opinion).
```docker exec -it open_loyalty_backend bash -c "curl -XGET 'http://elk:9200/_count?pretty' -d ' { "query": { "match_all": {} } } '"```

Try to call:

```docker exec -it open_loyalty_backend bash -c "curl --dump-header headers.txt -XGET 'http://elk:9200/_count?pretty' -d ' { "query": { "match_all": {} } } '"```

in order save response headers and display it:

```docker exec -it open_loyalty_backend bash -c "cat headers.txt"```

Moreover, calling:

```vagrant@open-loyalty:/opt/open-loyalty# curl -XGET 'http://172.18.0.3:9200/_count?pretty' -d ' { "query": { "match_all": {} } } '```

is invalid becuase you try to reach container within your host using docker private address.

**Comment by colejarczyk** [comment]
Closed after a long time without response
