### ISSUE TITLE
configure mailserver in demo version

### ISSUE THREAD

**Issue by aazzim** [DivanteLtd/open-loyalty#87]
i am running demo version and i need to know how to configure sending mail function to receive mails such as reset password. i didn't find any info about in the documents

**Comment by tjurczak** [comment]
Hi,

mail configuration is located in standard symfony configuration file ```backend/app/config/parameters.yml```. Configuration is described in https://symfony.com/doc/3.4/email.html

**Comment by aazzim** [comment]
great ,

what about if i activate the customer through API , how to set a password
for him ?

**Comment by tjurczak** [comment]
If you create customer through API (POST /api/customer/register) then user receive email with password.

**Comment by aazzim** [comment]
ok great for your prompt support
