### ISSUE TITLE
Permanent Token can not get the customer list

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#89]
I created a new admin account with a permanent api key.

I tested the key with **[GET] http://openloyalty.localhost/api/admin**, it worked.
But it did not work when it came to **[GET] http://openloyalty.localhost/api/customer**. It returned:

> {
>     "code": 401,
>     "message": "Invalid credentials"
> }

Is it a bug ?

**Comment by tjurczak** [comment]
Currently it's normal behaviour. If you want to use customer's endpoints you should get jwt token using normal process login for customer (/api/customer/login) or sales (/api/sales/login). Some endpoints from customer and sales namespace needs context of log in customer / salesman.

If you have to use some method from customer/sales namespace you can add additional routing to controller method.

**Comment by tjurczak** [comment]
Here we have the same situation. Endpoint http://openloyalty.localhost:8080/#!/admin/customers-list is accesible only for users whom logged in using ```/api/admin/login_check```. 

We will fix it 2.3.0 (will be provided in 1 hours).

Fix is simply. You need to add additional routing to ```\OpenLoyalty\Bundle\UserBundle\Controller\Api\CustomerController::listAction```

```     * @Route(name="oloy.customer.admin_list", path="/admin/customer")```

As a result firewalls defined in security.yml takes ```admin_api``` which support oloy.user.guard.token.

**Comment by catbuilts** [comment]
Ho @tjurczak 

It works now. Thank you.

**Comment by tjurczak** [comment]
Hi @catbuilts,

First of all clear the cache ```cache:clear```. Restarting container doesn't clear the cache.
Next try to check if routing exists in API Doc by http://openloyalty.localhost/doc or in dev mode http://openloyalty.localhost/app_dev.php/doc.

**Comment by catbuilts** [comment]
Dear @tjurczak 

Thanks ! It worked.
