### ISSUE TITLE
Can not pull "openloyalty/base-php-fpm" image in Develop Mode

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#91]
When I run in dev mode, it got stuck at this line:

> Step 2/25 : FROM openloyalty/base-php-fpm AS base
> ERROR: Service 'php' failed to build: pull access denied for openloyalty/base-php-fpm, repository does not exist or may require 'docker login'

In the previous version, docker pulls from `divante/open-loyalty-base-php-fpm`, and it's fine. But when version 2.3.0 comes out, its pull from `openloyalty/base-php-fpm` instead, and the error occurs. 
It's likely that `openloyalty/base-php-fpm`doesnt exist. 

Can you recheck this.

Thank you.

**Comment by tjurczak** [comment]
@catbuilts Hi,

It was our mistake, should be ```divante```. We fixed it.

**Comment by nguyen123** [comment]
please help me, i error

**Comment by hai-doan** [comment]
@nguyen123 Just update the image name in `docker/dev/web/front-dockerfile` to `divante/open-loyalty-base-nodejs`
