### ISSUE TITLE
An example for api/points/transfer/add

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#92]
In the issue #75 , I have asked a better solution to add points for many customers at the same time.
As @Arfeen suggested to use **api/points/transfer/add**, I try to use this api but I can only add points for 1 customer [1]. When it comes to a list of customers, it didn't work like I expected [2].

Can you please give me an example to use this api with a list of customers?
Thank you.

___________
 + **[1] When use the api with only 1 customer:**
```
{
	"transfer":
	{
		"customer": "653bbb4d-dc9e-4256-bfea-edaf94923b29",
		"points":223,
		"comment": "event_add"
	}
}
```

It responses well with status 200.

```
{
    "pointsTransferId": "4e775a26-35a6-45d9-9051-3d28bcecff62"
}
```

 + **[2] When use the api with a list of customers (e.g. 2 people):**

```
{
	"transfer":
	{
		"customer": ["653bbb4d-dc9e-4256-bfea-edaf94923b29", "a7ac4b93-eeae-481e-8aa5-0eea82f64dea"],
		"points":223,
		"comment": "event_add_point"
	}
}
```

It returns an error:

```
{
    "form": {
        "children": {
            "customer": {
                "errors": [
                    "This value is not valid."
                ]
            },
            "points": {},
            "comment": {}
        }
    },
    "errors": []
}
```

**Comment by arfeen** [comment]
@catbuilts I think you are right. Since its in "choice" type, that means you can add only 1 customer among many. There should be a feature for multiple customer ids.

**Comment by catbuilts** [comment]
@arfeen 
Thanks for your information.

So the problem is come back to #75

**Comment by colejarczyk** [comment]
Closed after a long time without response
