### ISSUE TITLE
Front End Spins

### ISSUE THREAD

**Issue by burkeyc** [DivanteLtd/open-loyalty#93]
I have installed this on a fresh Ubuntu 16.04.03 using the Vagrant instructions.  Here are the exact steps that I used to get it up and running. 
	•	sudo apt-get update
	•	sudo apt-get install virtualbox dpkg
	•	sudo apt-get install build-essential libssl-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip
	•	wget https://github.com/git/git/archive/v2.8.1.zip -O git.zip
	•	unzip git.zip
	•	cd git-*
	•	make prefix=/usr/local all
	•	sudo make prefix=/usr/local install
	•	cd ~
	•	git clone https://github.com/git/git.git
	•	cd git
	•	make prefix=/usr/local all
	•	sudo make prefix=/usr/local install
	•	git clone https://github.com/DivanteLtd/open-loyalty.git
	•	wget https://releases.hashicorp.com/vagrant/2.0.3/vagrant_2.0.3_x86_64.deb
	•	sudo dpkg -i vagrant_2.0.3_x86_64.deb
	•	vagrant up
	•	vagrant ssh
	•	docker-compose -f docker/docker-compose.yml up -d
	•	docker-compose -f docker/docker-compose.yml exec php phing demo 
I know that it is something stupid that I am missing but this is to be accessed from a remote machine.  Any advise on what needs to be changed to point the instance to something like openLoyalty.ABC.net

**Comment by tjurczak** [comment]
Hi @burkeyc,

Could you provide more information what is error? What addresses did you try to connect to remote machine?
Did you add host openloyalty.localhost as 127.0.0.1 in your system configuration file (/etc/hosts)?
Bellow addresses should be exposed after correct installation:

http://openloyalty.localhost:8182 - the administration panel,
http://openloyalty.localhost:8183 - the customer panel,
http://openloyalty.localhost:8184 - the merchant panel,
http://openloyalty.localhost:8181 - RESTful API port
http://openloyalty.localhost:8181/doc - swagger-like API doc

**Comment by colejarczyk** [comment]
Closed after a long time without response
