### ISSUE TITLE
Service 'php' failed to build

### ISSUE THREAD

**Issue by vmizev** [DivanteLtd/open-loyalty#94]
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
: No such file or directory
Service 'php' failed to build: The command '/bin/sh -c chmod a+x init.sh && rm web/app_dev.php && composer install --no-dev -o --prefer-dist & bin/console assets:install && rm web/config.php && chown -R www-data:www-data /var/www/openloyalty/var' returned a non-zero code: 127

I get this error following Quick install guide. Both Docker and Vagrant methods are failed with same error.
I've tried on Win10 and Ubuntu 16.04. On my another computer the same.

My steps:
1. Added `127.0.0.1 openloyalty.localhost` to hosts
2. `docker-compose up`
3. Error
---------------------------
1. `vagrant up`
2. `vagrant ssh`
3. `docker-compose -f docker/docker-compose.yml up -d`
4. Error

$ docker -v
Docker version 18.03.0-ce, build 0520e24

$ vagrant -v
Vagrant 2.0.3

![error](https://user-images.githubusercontent.com/22033070/38564398-bdbbc9a4-3ce7-11e8-8145-39220e3113c2.png)

**Comment by catbuilts** [comment]
Hi @vmizev 

Did you clone the project or download the zip file ?
When cloning, it misses some files which causes error. If you cloned, try to build again, but this time with the zip file.

**Comment by vmizev** [comment]
@catbuilts  Thanks a lot! Build from .zip works fine with Vagrant.
