### ISSUE TITLE
Upload csv files not working in windows

### ISSUE THREAD

**Issue by tharun148** [DivanteLtd/open-loyalty#95]
I have upload a campaign csv file in windows It says invalid csv format but working in ubuntu environment. No console errors

**Comment by tjurczak** [comment]
Hi,

Could you provide more information (error message, which way of upload has been used by you)?
This may be related to charset coding. Try to convert csv file to UTF-8 or change new line chars to unix.

**Comment by tharun148** [comment]
Fixed this by adding "application/vnd.ms-excel" in csv component thanks
