### ISSUE TITLE
general spend points calculation 

### ISSUE THREAD

**Issue by aazzim** [DivanteLtd/open-loyalty#96]
i didn't get how number of earned points calculated in the "general spend" loyalty role

what is the SKU and numbers mentioned [ 123 234 567 ] , i understood that Point value * field is how much customer has to spend to get specific number of points , how those SKUs values leads to 1 point

**Comment by HubertOL** [comment]
Hello,

The General spending rule is all about how much points the customer can earn by spending 1 amount of currency, I.e. if customer purchase for 100$ he can receive 100 points if the value in the "Point value = 1". If it's 10 points for 1 amount of money, the customer will receive 1000 points for 100$ spent.

SKU refers to Stock Keeping Unit - specific product in the stock. The sample SKU123 we've given is just an example. If OpenLoyalty is integrated with the product database, then information about the SKU should be pulled via API. 

You can exclude specific SKU (products) from the general spending rule if you run a discount campaign (i.e. in the e-commerce). In the same way, you can exclude shipping costs from that rule.
