### ISSUE TITLE
Admin tokens in Openloyalty

### ISSUE THREAD

**Issue by catbuilts** [DivanteLtd/open-loyalty#97]
Hi,

I have 2 questions about Admin token.
     
   * **Question number 1**: How long does the admin token remain alive ? 
I guess it can be used in 24 hours. Is there any way we can make it remain longer or even control its lifetime ?

   * **Question number 2**: How to protect Permanent token
It turns out that Permanent admin token is a better alternative for us to solve the question 1. But it's vulnerable because the admin can easily change it (which can lead the system to crash). I don't get the point here when the admin can edit this token. How can we protect this token against changes from the admin (just server's control only) ?

**Comment by colejarczyk** [comment]
Hi,

1. Yes, it's 24 hours. It's a configurable value in the app/config/parameters.yml. Please see a jwt_token_ttl: 86400. It can be extended to a greater value and it's defined in seconds.

2. I agree it's a better alternative however it's not protected. We assume that the administrators know what they are doing. The only way to protect this value is to change a code and application logic.

**Comment by colejarczyk** [comment]
Closed after a long time without response
